//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <JavaKit/JKJavaMethod.h>

@interface JKJavaConstructor : JKJavaMethod
{
}

- (id)shortDescription;
- (id)description;
- (id)returnType;
- (BOOL)isClassConstructor;
- (id)initWithName:(id)arg1 signature:(id)arg2 accessMask:(unsigned long long)arg3 attributes:(id)arg4;

@end

