//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableString.h"

@interface NSMutableString (PBXTSStringAdditions)
- (void)deleteAllCharactersInSet:(id)arg1;
- (void)deleteTrailingWhitespace;
- (void)deleteAllWhitespace;
- (void)deleteLeadingWhitespace;
- (void)deleteCharactersFromSet:(id)arg1 atIndex:(unsigned long long)arg2 options:(unsigned long long)arg3;
- (void)appendSubstringWithRange:(struct _NSRange)arg1 ofString:(id)arg2;
@end

