//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsSupport/PBXTSCharacterStream.h>

#import "PBXTSByteStreamConsuming.h"
#import "PBXTSStreamConsumerRetaining.h"

@interface PBXTSUTF8DecoderFilter : PBXTSCharacterStream <PBXTSByteStreamConsuming, PBXTSStreamConsumerRetaining>
{
    unsigned long long _numBufferedUTF8Bytes;
    unsigned char _bufferedUTF8Bytes[4];
}

- (void)streamDidEnd:(id)arg1;
- (void)stream:(id)arg1 processBytes:(id)arg2;

@end

