//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsCore/PBXProjectItem.h>

@class NSString, PBXBookmarkGroup, PBXProject;

@interface PBXBookmarkItem : PBXProjectItem
{
    NSString *_name;
    PBXBookmarkGroup *_bookmarkGroup;
    PBXProject *_project;
}

+ (id)archivableAttributes;
- (long long)compareUsingName:(id)arg1;
- (BOOL)shouldArchiveName;
- (void)setContainer:(id)arg1;
- (id)container;
- (void)setBookmarkGroup:(id)arg1;
- (id)bookmarkGroup;
- (void)setName:(id)arg1;
- (id)name;
- (id)defaultName;
- (void)dealloc;

@end

