//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsCore/XCLinkerSpecification.h>

@interface PBXLinkerSpecificationResMerger : XCLinkerSpecification
{
}

- (id)createCommandsforInputs:(id)arg1 inBuildContext:(id)arg2;

@end

