//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsCore/PBXObject.h>

@class NSArray, NSMutableDictionary;

@interface XCBreakpointAction : PBXObject
{
    BOOL _useDebuggerSideImplementation;
    NSArray *_expressions;
    NSMutableDictionary *_evaluatedExpressions;
}

+ (id)displayName;
+ (void)setAvailableActions:(id)arg1;
+ (id)availableActions;
+ (id)replaceExpressions:(id)arg1 inString:(id)arg2;
+ (id)expressionsInString:(id)arg1;
+ (id)archivableAttributes;
- (BOOL)allExpressionsEvaluated;
- (void)resetActionState;
- (id)evaluatedExpressions;
- (void)setExpressions:(id)arg1;
- (id)expressions;
- (void)actionWillBeRemovedFromBreakpoint:(id)arg1;
- (void)purify;
- (void)setUseDebuggerSideImplementation:(BOOL)arg1;
- (BOOL)useDebuggerSideImplementation;
- (void)performInSession:(id)arg1 onBreakpoint:(id)arg2;
- (id)editorClassName;
- (void)dealloc;
- (void)awakeFromPListUnarchiver:(id)arg1;
- (id)init;

@end

