//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsCore/XCPropertyDefinition.h>

@class NSArray;

@interface XCEnumerationPropertyDefinition : XCPropertyDefinition
{
    NSArray *_allowedValueDefns;
}

+ (BOOL)isListType;
+ (id)identifier;
- (id)argumentGenerationInfoProvidersForValue:(id)arg1;
- (id)localizedAllowedValues;
- (id)allowedValues;
- (void)dealloc;
- (id)initFromPListDictionary:(id)arg1;

@end

