//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSError, NSString, NSThread;

@interface XCOperation : NSObject
{
    NSString *_identifier;
    NSDictionary *_userInfo;
    int _state;
    int _resultCode;
    BOOL _shouldCancel;
    NSThread *_originatingThread;
    double _startTime;
    double _endTime;
    double _progress;
    NSError *_error;
}

+ (void)_recordNewRunningOperation:(id)arg1;
+ (id)activeOperations;
+ (id)operationArbitrator;
- (id)displayName;
- (int)cleanupAfterRunning;
- (int)runOperation;
- (int)setupBeforeRunning;
- (BOOL)shouldCancel;
- (id)error;
- (double)percentComplete;
- (double)endTime;
- (double)startTime;
- (BOOL)isRunning;
- (BOOL)isPending;
- (BOOL)isReadyToRunWithReasonForDelay:(id *)arg1;
- (int)resultCode;
- (int)state;
- (void)pendWasCancelledWithReason:(id)arg1;
- (void)cancel;
- (void)_cancelPendingOperation;
- (id)originatingThread;
- (void)stopWithResultCode:(int)arg1;
- (void)run;
- (void)runWhenReady;
- (void)_pendWithReason:(id)arg1;
- (void)setUserInfo:(id)arg1;
- (id)userInfo;
- (id)identifier;
- (void)finalize;
- (void)dealloc;
- (id)init;
- (id)initWithIdentifier:(id)arg1;

@end

