//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsCore/XCSearchPath.h>

@class NSData, PBXBTree;

@interface XCRecursiveSearchPath : XCSearchPath
{
    NSData *_stringData;
    const char *_stringDataPtr;
    PBXBTree *_entries;
}

+ (id)_searchPathRegistryDictionary;
- (void)_scanDirectories;
- (id)absolutePathMatchingEntryName:(id)arg1;
- (unsigned long long)count;
- (void)dealloc;

@end

