//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XcodeEdit/XCTextAnnotation.h>

@class PBXBreakpoint;

@interface XCBreakpointTextAnnotation : XCTextAnnotation
{
    PBXBreakpoint *_breakpoint;
}

+ (id)annotationWithBreakpoint:(id)arg1;
+ (unsigned long long)_defaultHighlightsByMask;
+ (id)_defaultAnnotationTheme;
+ (unsigned long long)_defaultSidebarMarkerAlignment;
+ (id)pendingBreakpointSidebarIcon;
+ (id)multipleBreakpointsSidebarIcon;
+ (id)breakpointSidebarIcon;
- (BOOL)isBreakpoint;
- (BOOL)wantsInvertedLineNumber;
- (long long)precedence;
- (void)drawSidebarMarkerInParagraphRect:(struct CGRect)arg1 firstLineRect:(struct CGRect)arg2 annotationRect:(struct CGRect)arg3 inView:(id)arg4;
- (id)sidebarMarkerIconImage;
- (struct CGSize)calculateAnnotationViewSizeForBounds:(struct CGRect)arg1;
- (id)createAnnotationViewForTextView:(id)arg1 withFrame:(struct CGRect)arg2;
- (void)noteThatDesiredSizeMayHaveChanged;
- (void)_breakpointDidChange:(id)arg1;
- (id)breakpoint;
- (void)dealloc;
- (id)initWithBreakpoint:(id)arg1;

@end

