//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "XCSpecification.h"

@class NSColor, NSString;

@interface XCSyntaxTypeSpecification : XCSpecification
{
    BOOL _inheritsColor;
    BOOL _isMark;
    BOOL _includeInPreferences;
    BOOL _ignoreToken;
    BOOL _isLink;
    NSString *_urlFormat;
    NSString *_nameFormat;
    NSString *_oldDefaultName;
    NSColor *_color;
}

+ (id)specificationRegistryName;
+ (id)specificationTypePathExtensions;
+ (id)localizedSpecificationTypeName;
+ (id)specificationType;
+ (Class)specificationTypeBaseClass;
- (id)color;
- (id)oldDefaultFont;
- (id)oldDefaultColor;
- (id)nameFormat;
- (id)urlFormat;
- (BOOL)isLink;
- (BOOL)ignoreToken;
- (BOOL)includeInPreferences;
- (BOOL)isMark;
- (BOOL)inheritsColor;
- (void)dealloc;
- (id)initWithPropertyListDictionary:(id)arg1 inDomain:(id)arg2;

@end

