//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsCParsing/Expression.h>

#import "ScopeLookup.h"

@class ASTNode<ScopeLookup>, NSMutableArray;

@interface DeclarationContainingStatement : Expression <ScopeLookup>
{
    NSMutableArray *_declarations;
    ASTNode<ScopeLookup> *_containingScope;
}

- (id)shortDescription;
- (BOOL)containsLocalDeclaration:(id)arg1;
- (id)lookupNameRecursively:(id)arg1 nameKind:(int)arg2 upTo:(id)arg3;
- (id)lookupName:(id)arg1 nameKind:(int)arg2;
- (id)findName:(id)arg1 nameKind:(int)arg2;
- (void)setContainingScope:(id)arg1;
- (void)addDeclaration:(id)arg1 project:(id)arg2;
- (id)declarations;
- (id)containingScope;
- (void)dealloc;
- (id)initWithContainingScope:(id)arg1;

@end

