//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IBLayoutConstant, IBLayoutConstraintMultiplier, NSObject<IBLayoutConstraintRepresentation>;

@protocol IBLayoutConstraintRepresentation <NSObject>
@property(readonly, nonatomic, getter=isPlaceholder) BOOL placeholder;
@property(readonly, nonatomic) double scoringType;
@property(readonly, nonatomic) long long scoringClass;
@property(readonly, nonatomic) id containingViewRepresentation;
@property(readonly, nonatomic) double priority;
@property(readonly, nonatomic) IBLayoutConstant *constant;
@property(readonly, nonatomic) IBLayoutConstraintMultiplier *multiplier;
@property(readonly, nonatomic) unsigned long long secondAttribute;
@property(readonly, nonatomic) id secondItemRepresentation;
@property(readonly, nonatomic) long long relation;
@property(readonly, nonatomic) unsigned long long firstAttribute;
@property(readonly, nonatomic) id firstItemRepresentation;
- (unsigned long long)hashOfComponents;
- (BOOL)hasComponentsEqualToComponentsOfRepresentationAllowingReversing:(NSObject<IBLayoutConstraintRepresentation> *)arg1;
- (BOOL)hasComponentsEqualToComponentsOfRepresentation:(NSObject<IBLayoutConstraintRepresentation> *)arg1;
- (NSObject<IBLayoutConstraintRepresentation> *)representationByReversingFirstAndSecondItem;
@end

