//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IBBinaryArchiving.h"
#import "IBLayoutConstraintRepresentation.h"
#import "NSCoding.h"
#import "NSCopying.h"

@class IBLayoutConstant, IBLayoutConstraintMultiplier, NSString;

@interface IBLayoutConstraintArchivableRepresentation : NSObject <NSCoding, NSCopying, IBLayoutConstraintRepresentation, IBBinaryArchiving>
{
    BOOL _placeholder;
    NSString *_firstItemIdentifier;
    unsigned long long _firstAttribute;
    long long _relation;
    NSString *_secondItemIdentifier;
    unsigned long long _secondAttribute;
    double _priority;
    IBLayoutConstraintMultiplier *_multiplier;
    IBLayoutConstant *_constant;
    NSString *_containingViewIdentifier;
    double _scoringType;
    long long _scoringClass;
    long long _contentType;
}

@property(readonly, nonatomic) long long contentType; // @synthesize contentType=_contentType;
@property(readonly, nonatomic) long long scoringClass; // @synthesize scoringClass=_scoringClass;
@property(readonly, nonatomic) double scoringType; // @synthesize scoringType=_scoringType;
@property(readonly, nonatomic) NSString *containingViewIdentifier; // @synthesize containingViewIdentifier=_containingViewIdentifier;
@property(readonly, nonatomic) IBLayoutConstant *constant; // @synthesize constant=_constant;
@property(readonly, nonatomic, getter=isPlaceholder) BOOL placeholder; // @synthesize placeholder=_placeholder;
@property(readonly, nonatomic) IBLayoutConstraintMultiplier *multiplier; // @synthesize multiplier=_multiplier;
@property(readonly, nonatomic) double priority; // @synthesize priority=_priority;
@property(readonly, nonatomic) unsigned long long secondAttribute; // @synthesize secondAttribute=_secondAttribute;
@property(readonly, nonatomic) NSString *secondItemIdentifier; // @synthesize secondItemIdentifier=_secondItemIdentifier;
@property(readonly, nonatomic) long long relation; // @synthesize relation=_relation;
@property(readonly, nonatomic) unsigned long long firstAttribute; // @synthesize firstAttribute=_firstAttribute;
@property(readonly, nonatomic) NSString *firstItemIdentifier; // @synthesize firstItemIdentifier=_firstItemIdentifier;
- (void).cxx_destruct;
- (id)representationByReversingFirstAndSecondItem;
- (unsigned long long)hashOfComponents;
- (BOOL)hasComponentsEqualToComponentsOfRepresentationAllowingReversing:(id)arg1;
- (BOOL)hasComponentsEqualToComponentsOfRepresentation:(id)arg1;
@property(readonly, nonatomic) id containingViewRepresentation;
@property(readonly, nonatomic) id secondItemRepresentation;
@property(readonly, nonatomic) id firstItemRepresentation;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithBinaryUnarchiver:(id)arg1;
- (void)encodeWithBinaryArchiver:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithLayoutConstraint:(id)arg1 withRepresentationForItemBlock:(CDUnknownBlockType)arg2;

@end

