//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DSADocSet, DTFileSystemEventStream, NSDate, NSString;

@interface DSMDocSetRecord : NSObject
{
    DSADocSet *_docSet;
    NSString *_name;
    NSString *_docSetID;
    NSString *_shortVersionString;
    NSString *_copyright;
    NSString *_feedName;
    NSString *_feedURL;
    NSString *_minimumXcodeVersion;
    NSString *_webRootURL;
    NSString *_path;
    BOOL _isDuplicate;
    BOOL _searchingEnabled;
    DTFileSystemEventStream *_eventStream;
    NSDate *_modificationDate;
}

@property(retain, nonatomic) NSDate *modificationDate; // @synthesize modificationDate=_modificationDate;
@property(nonatomic) BOOL searchingEnabled; // @synthesize searchingEnabled=_searchingEnabled;
@property(retain, nonatomic) DTFileSystemEventStream *eventStream; // @synthesize eventStream=_eventStream;
@property(nonatomic) BOOL isDuplicate; // @synthesize isDuplicate=_isDuplicate;
@property(copy, nonatomic) NSString *path; // @synthesize path=_path;
@property(copy, nonatomic) NSString *webRootURL; // @synthesize webRootURL=_webRootURL;
@property(copy, nonatomic) NSString *minimumXcodeVersion; // @synthesize minimumXcodeVersion=_minimumXcodeVersion;
@property(copy, nonatomic) NSString *feedURL; // @synthesize feedURL=_feedURL;
@property(copy, nonatomic) NSString *feedName; // @synthesize feedName=_feedName;
@property(copy, nonatomic) NSString *copyright; // @synthesize copyright=_copyright;
@property(copy, nonatomic) NSString *shortVersionString; // @synthesize shortVersionString=_shortVersionString;
@property(copy, nonatomic) NSString *docSetID; // @synthesize docSetID=_docSetID;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) DSADocSet *docSet; // @synthesize docSet=_docSet;
- (void)stopListeningToFileSystemEventStream;
- (void)prepareForRemoval;
- (void)createFileSystemEventStreamWithDelegate:(id)arg1;
- (id)description;
- (id)initWithDocSet:(id)arg1 atPath:(id)arg2;

@end

