//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFileManager.h"

@interface NSFileManager (DocSetPrivateAddition)
- (BOOL)_dr_createDirectoryAtPath:(id)arg1 attributes:(id)arg2;
@end

