//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DVTFileDataType, DVTFilePath, NSString;

@interface IDEBatchFindCandidateFile : NSObject
{
    DVTFilePath *_filePath;
    DVTFileDataType *_dataType;
    NSString *_groupTitle;
    BOOL _inLinkedFramework;
}

+ (void)purgeCachedFilePaths;
+ (id)cachedFileForPathString:(id)arg1;
+ (void)initialize;
@property(readonly) BOOL inLinkedFramework; // @synthesize inLinkedFramework=_inLinkedFramework;
@property(readonly) NSString *groupTitle; // @synthesize groupTitle=_groupTitle;
@property(readonly) DVTFilePath *filePath; // @synthesize filePath=_filePath;
- (void).cxx_destruct;
- (long long)compare:(id)arg1;
@property(readonly) DVTFileDataType *dataType; // @synthesize dataType=_dataType;
@property(readonly) NSString *pathExtension;
@property(readonly) NSString *name;
@property(readonly) NSString *path;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithPath:(id)arg1 fromSearchPath:(id)arg2;
- (id)initWithFileReference:(id)arg1 groupTitle:(id)arg2 inLinkedFramework:(BOOL)arg3;

@end

