//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSString;

@interface IDEInspectorCapsuleTextLozenge : NSViewController
{
    NSString *_stringValue;
}

@property(readonly) NSString *stringValue; // @synthesize stringValue=_stringValue;
- (void).cxx_destruct;
- (id)initWithStringValue:(id)arg1;

@end

