//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEKit/IDEActivityReporter.h>

@class IDEActivityReport;

@interface IDESnapshotActivityReporter : IDEActivityReporter
{
    id _snapshotStartObserver;
    id _snapshotEndObserver;
    id _snapshotRestoreStartObserver;
    id _snapshotRestoreEndObserver;
    IDEActivityReport *_activeCreationReport;
    IDEActivityReport *_activeRestoreReport;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)initWithWorkspace:(id)arg1;
- (void)_updateWithValue:(BOOL)arg1 forCreation:(BOOL)arg2;

@end

