//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IDENavigableItemRepresentation.h"

@class DVTDocumentLocation, DVTFileDataType, IDEFileReference, NSArray, NSImage, NSString;

@interface IDETestingHelperTestableProviderWrapper : NSObject <IDENavigableItemRepresentation>
{
    id <IDETestableProvider> _provider;
}

+ (id)keyPathsAffectingTestableWrappers;
@property(retain) id <IDETestableProvider> provider; // @synthesize provider=_provider;
- (void).cxx_destruct;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) NSString *navigableItem_name;
@property(readonly) NSArray *testableWrappers;
- (id)initWithTestableProvider:(id)arg1;

// Remaining properties
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) IDEFileReference *navigableItem_fileReference;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) BOOL navigableItem_isLeaf;
@property(readonly) BOOL navigableItem_isMajorGroup;

@end

