//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CFNetwork/__NSCFSessionBridge.h>

@class __NSCFURLSession;

__attribute__((visibility("hidden")))
@interface __NSCFLocalSessionBridge : __NSCFSessionBridge
{
    __NSCFURLSession *_session;
    unsigned long long _identSeed;
    struct __CFURLConnectionSession *_connectionSession;
    struct __CFDictionary *_tasks;
    struct dispatch_queue_s *_invalidateQueue;
    CDUnknownBlockType _invalidateCallback;
}

- (const struct ClassicConnectionSession *)classicConnectionSession;
- (void)invalidateSession:(BOOL)arg1 withQueue:(struct dispatch_queue_s *)arg2 completion:(CDUnknownBlockType)arg3;
- (void)flushStorageWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)resetStorageWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)task:(id)arg1 didReceiveData:(struct dispatch_data_s *)arg2;
- (void)task:(id)arg1 challenged:(struct _CFURLAuthChallenge *)arg2 authCallback:(CDUnknownBlockType)arg3;
- (void)task:(id)arg1 request:(struct _CFURLRequest *)arg2 needsNewBodyStreamCallback:(CDUnknownBlockType)arg3;
- (void)task:(id)arg1 didFinishLoadingWithError:(struct __CFError *)arg2;
- (void)taskDidFinishLoading:(id)arg1;
- (void)task:(id)arg1 willCacheResponse:(struct _CFCachedURLResponse *)arg2 responseCallback:(CDUnknownBlockType)arg3;
- (void)task:(id)arg1 didReceiveResponse:(struct _CFURLResponse *)arg2;
- (void)task:(id)arg1 wasRedirected:(struct _CFURLResponse *)arg2 newRequest:(struct _CFURLRequest *)arg3 responseCallback:(CDUnknownBlockType)arg4;
- (void)taskTerminating:(id)arg1;
- (void)_onqueue_checkForCompletion;
- (void)_onqueue_invokeInvalidateCallback;
- (void)taskCreated:(id)arg1;
- (void)operationCompleted:(id)arg1;
- (void)bridgeInvalidated:(id)arg1;
- (void)task:(id)arg1 sentBodyBytes:(id)arg2 totalBytes:(id)arg3 expectedBytes:(id)arg4;
- (void)statusMessage:(struct __CFString *)arg1;
- (void)_onqueue_withDownloadTaskForSession:(id)arg1 perform:(CDUnknownBlockType)arg2;
- (void)_onqueue_withDataTaskForSession:(id)arg1 perform:(CDUnknownBlockType)arg2;
- (id)downloadTaskForRequest:(id)arg1 resumeData:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)uploadTaskForRequest:(id)arg1 uploadFile:(id)arg2 bodyData:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)dataTaskForRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)taskForClass:(Class)arg1 request:(id)arg2 uploadFile:(id)arg3 bodyData:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)_onqueue_connectUploadTask:(id)arg1 strippedRequest:(id)arg2 bodyStream:(id)arg3 bodyParts:(id)arg4;
- (id)copyTasks;
- (void)replaceTask:(id)arg1 withDownloadTask:(id)arg2;
- (void)dealloc;
- (id)initWithConfiguration:(id)arg1 session:(id)arg2 queue:(struct dispatch_queue_s *)arg3;
- (void)demuxv:(struct __CFString *)arg1 args:(struct __va_list_tag [1])arg2;
- (id)connToTask:(struct _CFURLConnection *)arg1;

@end

