//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying.h"

@class NSColor, NSMapTable;

@interface _NSStateMarker : NSObject <NSCopying>
{
    short _type;
    NSMapTable *_placeholderRegistry;
    NSMapTable *_cachedPlaceholderRegistry;
    NSColor *_textColor;
    unsigned long long _placeholderBindingsMask;
}

- (id)defaultPlaceholderForBinding:(id)arg1 onObjectClass:(Class)arg2;
- (void)setDefaultPlaceholder:(id)arg1 forBinding:(id)arg2 onObjectClass:(Class)arg3;
- (id)defaultTextColor;
- (void)setDefaultTextColor:(id)arg1;
- (id)description;
- (id)valueForKey:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)_hash;
- (id)copy;
- (oneway void)release;
- (unsigned long long)retainCount;
- (id)autorelease;
- (id)retain;
- (short)_type;
- (void)dealloc;
- (id)initWithType:(long long)arg1;

@end

