//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEKit/AAVAssistant.h>

@class AAVAssistantProgressView, DVTNotificationToken, NSProgressIndicator, NSString, NSTextField;

@interface AAVProgressAssistant : AAVAssistant
{
    DVTNotificationToken *_viewToken;
    NSProgressIndicator *progressIndicator;
    AAVAssistantProgressView *progressView;
    NSTextField *progressField;
    NSString *progressMessage;
}

+ (id)defaultViewNibName;
+ (BOOL)wantsOverlayEffect;
@property(retain) NSString *progressMessage; // @synthesize progressMessage;
@property(retain) NSTextField *progressField; // @synthesize progressField;
@property(retain) AAVAssistantProgressView *progressView; // @synthesize progressView;
@property(retain) NSProgressIndicator *progressIndicator; // @synthesize progressIndicator;
- (void).cxx_destruct;
- (void)taskDidFinishWithError:(id)arg1;
- (void)goBackWithError:(id)arg1;
- (void)alertEnded:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)loadView;
- (void)viewWillUninstall;
- (void)primitiveInvalidate;

@end

