//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol ABAccountCustomizationPolicy <NSObject>
- (NSString *)defaultAccountDescription;
- (long long)sortOrder;
- (BOOL)supportsPhotos;
- (BOOL)supportsPhoneticName;
- (BOOL)supportsDistributionLists;
- (BOOL)usesSyncServices;
- (BOOL)canReimportFromMetadata;
- (BOOL)canBecomeDefaultAccount;
- (BOOL)groupsCanRemoveMembers;
- (BOOL)showAllContactsIfOnlyOneGroup;
- (NSString *)directoryLabelForAccountName:(NSString *)arg1;
- (NSString *)allContactsLabelForAccountName:(NSString *)arg1;
@end

