//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AddressBook/ABAccountStatus.h>

@class NSImage, NSString;

__attribute__((visibility("hidden")))
@interface ABAccountImageStatus : ABAccountStatus
{
    NSString *_imageName;
    NSString *_pressedImageName;
}

@property(readonly) NSString *pressedImageName; // @synthesize pressedImageName=_pressedImageName;
@property(readonly) NSString *imageName; // @synthesize imageName=_imageName;
@property(readonly) NSImage *pressedImage;
@property(readonly) NSImage *image;
- (id)makeAccessoryView;
- (id)description;
- (void)dealloc;
- (id)initWithState:(unsigned long long)arg1 imageName:(id)arg2 pressedImageName:(id)arg3 target:(id)arg4 action:(SEL)arg5;

@end

