//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AddressBook/ABBrowsingGroupEntry.h>

@class ABAccount, ABAddressBook;

__attribute__((visibility("hidden")))
@interface ABAccountBrowsingGroupEntry : ABBrowsingGroupEntry
{
    ABAccount *_account;
    ABAddressBook *_addressBook;
}

+ (id)identifierForAccount:(id)arg1;
@property(readonly) ABAddressBook *addressBook; // @synthesize addressBook=_addressBook;
@property(readonly) ABAccount *account; // @synthesize account=_account;
- (id)description;
- (id)iconWithStyleProvider:(id)arg1;
- (BOOL)containsPeople:(id)arg1;
- (BOOL)shouldImportToDefaultAccount;
- (BOOL)canDrop;
- (BOOL)canCreateGroupFromSelection;
- (id)createHelperWithFactory:(id)arg1;
- (BOOL)canCreatePeople;
- (BOOL)canDeletePeople;
- (BOOL)canCreateGroup;
- (id)actionScope;
- (void)dealloc;
- (id)initWithName:(id)arg1 account:(id)arg2 addressBook:(id)arg3;

@end

