//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABCardViewMultiValue.h"

@class NSImage, NSString;

@protocol ABCardViewMutableMultiValue <ABCardViewMultiValue>
- (void)setAccountBadge:(NSImage *)arg1 atIndex:(unsigned long long)arg2;
- (void)setIsPrivateValue:(BOOL)arg1 index:(unsigned long long)arg2;
- (void)setReadOnly:(BOOL)arg1 atIndex:(unsigned long long)arg2;
- (void)replaceAccountNameAtIndex:(unsigned long long)arg1 withAccountName:(NSString *)arg2;
- (void)replaceLabelAtIndex:(unsigned long long)arg1 withLabel:(id)arg2;
- (void)removeEntryAtIndex:(unsigned long long)arg1;
- (void)replaceValueAtIndex:(unsigned long long)arg1 withValue:(id)arg2;
- (NSString *)addValue:(id)arg1 withLabel:(NSString *)arg2;
- (NSString *)addEmptyValueWithLabel:(NSString *)arg1;
- (NSString *)addEmptyValueAndLabel;
@end

