//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface ABCardViewPropertyProvider : NSObject
{
}

+ (id)relatedNamesProperty;
+ (id)phoneNumberProperty;
+ (id)urlAddressProperty;
+ (id)emailAddressProperty;
+ (id)postalAddressProperty;
+ (id)instantMessageProperty;
+ (id)socialProfileProperty;
+ (id)birthdayProperty;
+ (id)maidenNameProperty;
+ (id)preferredForNameProperty;
+ (id)linkedPeopleProperty;
+ (id)noteProperty;
+ (id)otherDatesProperty;
+ (id)keyToPropertyDictionary;
+ (id)propertyForKey:(id)arg1;

@end

