//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableArray;

@interface ABConstraintsBuilder : NSObject
{
    NSDictionary *_metrics;
    NSDictionary *_views;
    NSMutableArray *_constraints;
    unsigned long long _direction;
    long long _firstHorizontalAttribute;
    long long _secondHorizontalAttribute;
}

- (id)constraints;
- (void)horizontallyAlignViews:(id)arg1 withSpacing:(double)arg2;
- (void)horizontallyAlignVisibleViews:(id)arg1 withSpacing:(double)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (void)addConstraintWithItem:(id)arg1 attribute:(long long)arg2 relatedBy:(long long)arg3 toItem:(id)arg4 attribute:(long long)arg5 multiplier:(double)arg6 constant:(double)arg7;
- (id)mergedViewsWithExtraViews:(id)arg1;
- (id)constraintWithGenericFormat:(id)arg1;
- (void)addVisualConstraints:(id)arg1 withExtraViews:(id)arg2;
- (void)addAllVisualConstraints:(id)arg1 withExtraViews:(id)arg2;
- (void)addAllVisualConstraints:(id)arg1;
- (void)setUpHorizontalAttributesWithDirection:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithMetrics:(id)arg1 views:(id)arg2 direction:(unsigned long long)arg3;

@end

