//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface ABCustomPropertyCache : NSObject
{
    NSMutableDictionary *_propertiesByNameByRecordTypeByPersistentStore;
}

+ (id)storeIdentifierForStore:(id)arg1;
- (id)nts_propertiesByNameForRecordType:(id)arg1 inPropertiesByNameByRecordType:(id)arg2;
- (id)nts_propertiesByNameByRecordTypeForstoreIdentifier:(id)arg1;
- (void)nts_cacheCustomProperty:(id)arg1 forPropertyName:(id)arg2 recordType:(id)arg3 persistentStoreIdentifier:(id)arg4;
- (void)cacheCustomProperties:(id)arg1 withRecordType:(id)arg2;
- (id)cachedCustomPropertiesByNameForRecordType:(id)arg1 persistentStore:(id)arg2;
- (id)customPropertyDescriptionsByNameWithRecordType:(id)arg1 inManagedObjectContext:(id)arg2 persistentStore:(id)arg3;
- (id)customPropertyDescriptionsWithRecordType:(id)arg1 inContext:(id)arg2 persistentStore:(id)arg3;
- (id)customPropertyWithName:(id)arg1 recordType:(id)arg2 inContext:(id)arg3 persistentStore:(id)arg4;
- (id)customPropertyDescriptionWithName:(id)arg1 recordType:(id)arg2 inContext:(id)arg3 persistentStore:(id)arg4;
- (void)clearCustomPropertyCaches;
- (void)accountRepositoryDidChange:(id)arg1;
- (void)dealloc;
- (id)init;

@end

