//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ABFuture.h"

@class ABFutureCompletionBlocks, ABFutureResult, ABTask, NSConditionLock;

@interface ABFutureTask : NSObject <ABFuture>
{
    NSConditionLock *_stateLock;
    ABFutureResult *_futureResult;
    ABTask *_task;
    ABFutureCompletionBlocks *_completionBlocks;
}

- (id)futureResult;
- (void)addFailureBlock:(CDUnknownBlockType)arg1;
- (void)addSuccessBlock:(CDUnknownBlockType)arg1;
- (BOOL)finishWithError:(id)arg1;
- (BOOL)finishWithResult:(id)arg1;
- (BOOL)finishWithResult:(id)arg1 error:(id)arg2;
- (BOOL)run;
- (void)didCancel;
- (BOOL)cancel;
- (BOOL)nts_isFinished;
@property(readonly, getter=isCancelled) BOOL cancelled;
@property(readonly, getter=isFinished) BOOL finished;
- (id)resultBeforeDate:(id)arg1 error:(id *)arg2;
- (id)result:(id *)arg1;
- (void)dealloc;
- (id)initWithTask:(id)arg1;
- (id)init;

@end

