//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ABGroupListStyleProvider.h"

@interface ABGroupListStyleProvider : NSObject <ABGroupListStyleProvider>
{
}

+ (id)styleProvider;
- (id)directoryString;
- (id)smartGroupIcon;
- (id)lastImportIcon;
- (id)groupIcon;
- (id)folderIcon;
- (id)directoryIcon;
- (id)accountIcon;

@end

