//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AddressBook/ABDatumView.h>

@class ABLabelPopUpButton, NSTextField;

__attribute__((visibility("hidden")))
@interface ABInstantMessageDatumView : ABDatumView
{
    ABLabelPopUpButton *mServiceLabelButton;
    NSTextField *mServiceLabel;
    BOOL mNeedsReflow;
}

- (void)setServicePopUpEnabled:(BOOL)arg1;
- (void)setServiceLabelVisible:(BOOL)arg1;
- (void)setService:(id)arg1;
- (void)setServiceMenu:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)didInsertIntoCollectionView:(id)arg1;
- (id)updateKeyViewLoop;
- (struct CGRect)rectForServiceButtonWithMaxWidth:(double)arg1;
- (struct CGRect)contentRegionForView:(id)arg1 margin:(double)arg2;
- (void)_resizeTextField;
- (void)adjustInternalLayoutForLabelFrame:(struct CGRect *)arg1 valueFrame:(struct CGRect *)arg2;
- (void)dealloc;
- (void)awakeFromNib;

@end

