//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class ABPhoneFormatter, NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface ABLargeTypeView : NSView
{
    NSString *_phoneString;
    NSDictionary *_attributes;
    ABPhoneFormatter *_formatter;
}

- (void)mouseDown:(id)arg1;
- (BOOL)becomeFirstResponder;
- (BOOL)acceptsFirstResponder;
- (void)drawRect:(struct CGRect)arg1;
- (void)setAttributes:(id)arg1;
- (void)setPhoneString:(id)arg1;
- (struct CGRect)contentRectForString;
- (void)dealloc;

@end

