//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSMutableDictionary, NSRecursiveLock, NSString;

@interface ABLDAP_Manager : NSObject
{
    struct __ABLDAPManagerflags {
        unsigned int interestedInResults:1;
        unsigned int _reserved:31;
    } _flags;
    int _maxResults;
    int _timeLimit;
    long long _resultsCounter;
    int _numAttributes;
    NSMutableArray *_tempResults;
    NSString *_sessionUID;
    NSString *_LDAP_QueryString;
    NSString *_DS_QueryString;
    NSArray *_DS_QueryComponents;
    NSMutableArray *_LDAP_QueryAttributes;
    NSMutableArray *_binaryAttributes;
    NSArray *_capitalizedAttributes;
    NSArray *_lowercasedAttributes;
    char **_queryAttributes;
    NSRecursiveLock *_lock;
    NSMutableDictionary *_threadDict;
}

+ (void)cancelAllQueries;
+ (id)sharedLDAPManagerInstance;
- (void)postQueryHasBeenCanceledNotification;
- (void)postQueryHasFinishedNotification;
- (void)postResultsAreInNotificationNotification:(id)arg1;
- (BOOL)backgrounQueriesRunning;
- (void)makeQueries:(id)arg1;
- (id)allowedFields;
- (id)directoryServicesNodes;
- (void)freeAttributes;
- (void)resetLDAPManager;
- (void)notifyDataIsReady;
- (void)cancelQueries:(BOOL)arg1;
- (void)addEntries:(id)arg1 fromSession:(id)arg2;
- (void)setThread:(id)arg1 withObject:(id)arg2 withSessionUID:(id)arg3;
- (BOOL)startQueryForString:(id)arg1 withServers:(id)arg2 userInfo:(id)arg3 exactString:(BOOL)arg4;
- (BOOL)startQueryForString:(id)arg1 withServers:(id)arg2;
- (int)numberOfThreadsAlive;
- (void)decrementNumberOfThreadsAlive:(id)arg1 withSessionUID:(id)arg2;
- (int)queryOperator;
- (id)DSQueryComponents;
- (id)DSQueryString;
- (id)LDAPQueryString;
- (id)makeUID;
- (void)removeServer:(id)arg1;
- (void)setServer:(id)arg1;
- (id)sessionUID;
- (void)setSessionUID:(id)arg1;
- (id)recognizableAttributes;
- (id)lowercasedAttributes;
- (id)capitalizedAttributes;
- (char **)queryAttributes;
- (id)binaryAttributes;
- (void)setLowercasedAttributes:(id)arg1;
- (void)setCapitalizedAttributes:(id)arg1;
- (void)setQueryAttributes:(id)arg1;
- (void)setBinaryAttributes:(id)arg1;
- (int)timeLimit;
- (void)setTimeLimit:(int)arg1;
- (int)maxResults;
- (void)setMaxResults:(int)arg1;
- (BOOL)serverExists:(id)arg1 inServerList:(id)arg2;
- (void)addServer:(id)arg1;
- (id)directoryServicesServer;
- (id)availableUserServers;
- (id)deserializeServers:(id)arg1;
- (id)serializeServers:(id)arg1;
- (void)setServersInDefaultsFile:(id)arg1;
- (id)loadServersFromDefaultsFile;
- (id)defaultAddressBookPreferencesFile;
- (void)finalize;
- (void)dealloc;
- (id)init;

@end

