//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AddressBook/ABNameComponents.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface ABMutableNameComponents : ABNameComponents
{
}

@property BOOL isCompany; // @dynamic isCompany;
@property(copy) NSString *companyName; // @dynamic companyName;
@property(copy) NSString *suffix; // @dynamic suffix;
@property(copy) NSString *title; // @dynamic title;
@property(copy) NSString *middleName; // @dynamic middleName;
@property(copy) NSString *lastName; // @dynamic lastName;
@property(copy) NSString *firstName; // @dynamic firstName;

@end

