//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AddressBook/ABMultiValue.h>

@interface ABMutableMultiValue : ABMultiValue
{
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)_removeValue:(id)arg1;
- (BOOL)setPrimaryIdentifier:(id)arg1;
- (BOOL)replaceLabelAtIndex:(unsigned long long)arg1 withLabel:(id)arg2;
- (BOOL)replaceValueAtIndex:(unsigned long long)arg1 withValue:(id)arg2;
- (BOOL)removeValueAndLabelAtIndex:(unsigned long long)arg1;
- (void)_sortIdentifiersUsingComparator:(CDUnknownBlockType)arg1;
- (void)_sortLabelsUsing:(id)arg1;
- (void)_moveContentsAt:(unsigned long long)arg1 toIndex:(unsigned long long)arg2;
- (void)_appendValue:(id)arg1 withLabel:(id)arg2 andIdentifier:(id)arg3;
- (void)_combineWithMultiValue:(id)arg1 updating:(BOOL)arg2;
- (id)insertValue:(id)arg1 withLabel:(id)arg2 atIndex:(unsigned long long)arg3;
- (id)addValue:(id)arg1 withLabel:(id)arg2;
- (void)_createArrays;
- (id)_initWithIdentifiers:(id)arg1 values:(id)arg2 labels:(id)arg3 primaryIdentifier:(id)arg4;

@end

