//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import "NSOutlineViewDataSource.h"
#import "NSOutlineViewDelegate.h"

@class ABGroupEntriesList, ABPeoplePickerGroupListStyleProvider, ABPeoplePickerGroupListView, NSString;

__attribute__((visibility("hidden")))
@interface ABPeoplePickerGroupListController : NSViewController <NSOutlineViewDataSource, NSOutlineViewDelegate>
{
    ABPeoplePickerGroupListView *_outlineView;
    id <ABGroupHelperFactory> _helperFactory;
    BOOL _didAwakeFromNib;
    ABGroupEntriesList *_groupEntriesList;
    ABPeoplePickerGroupListStyleProvider *_groupListStyleProvider;
    NSString *_selectedGroupEntryIdentifier;
}

@property ABPeoplePickerGroupListView *outlineView; // @synthesize outlineView=_outlineView;
@property id <ABGroupHelperFactory> helperFactory; // @synthesize helperFactory=_helperFactory;
@property(copy) NSString *selectedGroupEntryIdentifier; // @synthesize selectedGroupEntryIdentifier=_selectedGroupEntryIdentifier;
@property(retain, nonatomic) ABGroupEntriesList *groupEntriesList; // @synthesize groupEntriesList=_groupEntriesList;
- (BOOL)groupListHasFocus;
- (void)selectGroupEntryWithIdentifier:(id)arg1;
- (void)selectGroupEntry:(id)arg1;
- (BOOL)canSelectEntryAtRow:(long long)arg1;
- (long long)selectableRowForPreviouslySelectedRow:(long long)arg1;
- (void)reloadAndRestoreSelection;
- (id)groupEntries;
- (void)groupEntriesDidChange:(id)arg1;
- (void)deselectGroup:(id)arg1;
- (void)selectGroup:(id)arg1 byExtendingSelection:(BOOL)arg2;
- (id)selectedGroups;
- (void)selectRow:(long long)arg1 byExtendingSelection:(BOOL)arg2;
- (void)deselectAll:(id)arg1;
- (void)selectAll:(id)arg1;
- (void)writeGroupUIDs:(id)arg1 toPasteboard:(id)arg2;
- (id)outlineView:(id)arg1 namesOfPromisedFilesDroppedAtDestination:(id)arg2 forDraggedItems:(id)arg3;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (BOOL)canDragEntries:(id)arg1;
- (id)childrenForEntry:(id)arg1;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (id)outlineView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;
- (id)outlineView:(id)arg1 persistentObjectForItem:(id)arg2;
- (id)outlineView:(id)arg1 itemForPersistentObject:(id)arg2;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineViewNeedsIndentation:(id)arg1;
@property BOOL hasBorder;
@property BOOL allowsMultipleSelection;
@property BOOL allowsEmptySelection;
@property SEL doubleAction;
@property(retain) id target;
- (void)dealloc;
- (void)awakeFromNib;

@end

