//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ABAddressBook, ABGroup, NSMutableArray;

@interface ABRemoveMembersCommandBuilder : NSObject
{
    ABGroup *_group;
    NSMutableArray *_memberIdentifiers;
    ABAddressBook *_addressBook;
}

- (id)build;
- (void)removeMember:(id)arg1;
@property(readonly) unsigned long long countOfRemovedMembers;
- (void)dealloc;
- (id)initWithGroup:(id)arg1 addressBook:(id)arg2;

@end

