//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ABSocialProfileURLParser : NSObject
{
}

+ (id)serivicesDictionary;
+ (id)parseURLStringByInference:(id)arg1;
+ (void)enumerateMatchesWithRegexPattern:(id)arg1 inString:(id)arg2 withBlock:(CDUnknownBlockType)arg3;
+ (void)enumerateServiceMatchesForURLString:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
+ (id)parseURLStringWithRegularExpressions:(id)arg1;
+ (id)parseSocialProfileURL:(id)arg1;

@end

