//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ABAccountCollection.h"

@class ABAccount, NSArray, NSString;

@interface ABStaticAccountCollection : NSObject <ABAccountCollection>
{
    NSString *_basePath;
    NSArray *_accounts;
    unsigned long long _indexOfDefaultAccount;
    NSString *_tag;
}

+ (id)collectionWithBasePath:(id)arg1 accounts:(id)arg2;
@property(copy) NSString *tag; // @synthesize tag=_tag;
- (id)accountWithIdentifier:(id)arg1;
@property(readonly) ABAccount *defaultAccount;
@property(readonly) NSArray *persistentAccounts;
@property(readonly) NSArray *enabledAccounts;
@property(readonly) NSArray *allAccounts;
@property(readonly) NSString *basePath;
- (void)dealloc;
- (id)initWithBasePath:(id)arg1 accounts:(id)arg2 indexOfDefaultAccount:(unsigned long long)arg3;

@end

