//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ABCommandVisitor.h"

__attribute__((visibility("hidden")))
@interface ABUndoableCommandVisitor : NSObject <ABCommandVisitor>
{
    CDUnknownBlockType _didExecuteCommandWithSaveRequest;
}

+ (id)visitor;
+ (id)executeRedoVisitor;
+ (id)executeUndoVisitor;
+ (id)executeVisitor;
@property(copy, nonatomic) CDUnknownBlockType didExecuteCommandWithSaveRequest; // @synthesize didExecuteCommandWithSaveRequest=_didExecuteCommandWithSaveRequest;
- (void)postProcessSaveRequest:(id)arg1;
- (id)makeSaveRequest;
- (void)visitSaveRequestCommand:(id)arg1;
- (void)visitUndoableCommand:(id)arg1;
- (void)visitCommand:(id)arg1;
- (void)dealloc;

@end

