//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSFormatter.h>

@class NSDateFormatter;

__attribute__((visibility("hidden")))
@interface ABvCardDateComponentsFormatter : NSFormatter
{
    NSDateFormatter *_compactYearMonthDayDateFormatter;
    NSDateFormatter *_compactYearMonthDayDateHourMinuteSecondZFormatter;
    NSDateFormatter *_monthDayDateFormatter;
    NSDateFormatter *_yearMonthDayDateFormatter;
    NSDateFormatter *_yearMonthDayDateHourMinuteSecondZFormatter;
}

- (BOOL)getObjectValue:(id *)arg1 forString:(id)arg2 errorDescription:(id *)arg3;
- (id)stringForObjectValue:(id)arg1;
- (id)yearMonthDayStringFromDateComponents:(id)arg1;
- (id)monthDayStringFromDateComponents:(id)arg1;
- (id)dateComponentsFromString:(id)arg1;
- (id)compactYearMonthDayDateHourMinuteSecondZFormatter;
- (id)compactYearMonthDayDateFormatter;
- (id)yearMonthDayDateFormatter;
- (id)yearMonthDayDateHourMinuteSecondZFormatter;
- (id)monthDayDateFormatter;
- (id)stringFromDateComponents:(id)arg1;
- (void)dealloc;

@end

