//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ABAccount, ABVCardLexer, ABvCardDateComponentsFormatter, NSArray, NSData, NSDateComponents, NSMutableArray, NSMutableDictionary, NSMutableString, NSString;

@interface ABVCardParser : NSObject
{
    ABVCardLexer *_lexer;
    NSData *_data;
    unsigned long long _defaultEncoding;
    BOOL _hasImportErrors;
    ABvCardDateComponentsFormatter *_dateComponentsFormatter;
    id <ABVCardValueSetter> _valueSetter;
    BOOL _30vCard;
    NSString *_first;
    NSString *_last;
    NSString *_org;
    NSString *_formattedName;
    NSDateComponents *_bday;
    NSMutableArray *_emails;
    NSMutableArray *_dateComponents;
    NSMutableArray *_phones;
    NSMutableArray *_addresses;
    NSMutableArray *_relatedNames;
    NSMutableArray *_urls;
    NSMutableArray *_calendarURIs;
    NSMutableString *_notes;
    NSMutableString *_otherNotes;
    NSMutableDictionary *_extensions;
    NSMutableArray *_unknowns;
    NSString *_uid;
    NSString *_carddavUID;
    NSMutableArray *_imHandles;
    NSMutableArray *_socialProfiles;
    NSMutableArray *_cropRects;
    BOOL _fullNameHasZeroLength;
    NSData *_imageData;
    NSString *_imageGroup;
    NSString *_imageReference;
    NSArray *_itemParameters;
    NSString *_grouping;
    unsigned long long _encoding;
    BOOL _quotedPrintable;
    BOOL _base64;
    NSMutableDictionary *_paramCache;
    ABAccount *_account;
}

+ (SEL)handlerSelectorForParameter:(id)arg1;
+ (SEL)parsingSelectorForTag:(id)arg1;
+ (unsigned long long)inferredStringEncodingFromData:(id)arg1;
+ (id)parserWithData:(id)arg1;
+ (id)dictionaryRepresentationOfVCardAtPath:(id)arg1;
@property(retain) id <ABVCardValueSetter> valueSetter; // @synthesize valueSetter=_valueSetter;
@property(retain) NSMutableArray *imHandles; // @synthesize imHandles=_imHandles;
- (BOOL)advancePastSemicolon;
- (id)nextStringValue;
- (void)parameter_ENCODING:(id)arg1;
- (void)parameter_CHARSET:(id)arg1;
- (void)parameter_BASE64:(id)arg1;
- (void)parameter_QUOTED_PRINTABLE:(id)arg1;
- (id)parseParameterValues;
- (id)nextParameterInCurrentLine;
- (id)parseParameters;
- (BOOL)parse_X_ADDRESSBOOKSERVER_PHONEME_DATA;
- (BOOL)parse_X_YAHOO_ID;
- (BOOL)parse_X_YAHOO;
- (BOOL)parse_X_SOCIALPROFILE;
- (BOOL)parse_X_SKYPE_ID;
- (BOOL)parse_X_SKYPE;
- (BOOL)parse_X_QQ_ID;
- (BOOL)parse_X_QQ;
- (BOOL)parse_X_PHONETIC_MIDDLE_NAME;
- (BOOL)parse_X_PHONETIC_LAST_NAME;
- (BOOL)parse_X_PHONETIC_FIRST_NAME;
- (BOOL)parse_X_MSN_ID;
- (BOOL)parse_X_MSN;
- (BOOL)parse_X_MAIDENNAME;
- (BOOL)parse_X_JABBER_ID;
- (BOOL)parse_X_JABBER;
- (BOOL)parse_X_ICQ_ID;
- (BOOL)parse_X_ICQ;
- (BOOL)parse_X_GTALK;
- (BOOL)parse_X_GOOGLE_ID;
- (BOOL)parse_X_ABUID;
- (BOOL)parse_X_ABSHOWAS;
- (BOOL)parse_X_ABRELATEDNAMES;
- (BOOL)parse_X_AIM_ID;
- (BOOL)parse_X_AIM;
- (BOOL)parse_X_ABPHOTO;
- (BOOL)parse_X_ABORDER;
- (BOOL)parse_X_ABLABEL;
- (BOOL)parse_X_ABDATE;
- (BOOL)parse_X_ABADR;
- (BOOL)parse_VERSION;
- (BOOL)parse_URL;
- (BOOL)parse_UID;
- (BOOL)parse_TITLE;
- (BOOL)parse_TEL;
- (BOOL)parse_REV;
- (BOOL)parse_PRODID;
- (BOOL)parse_PHOTO;
- (BOOL)parse_ORG;
- (BOOL)parse_NOTE;
- (BOOL)parse_NICKNAME;
- (BOOL)parse_N;
- (BOOL)parse_IMPP;
- (BOOL)parse_FN;
- (BOOL)parse_EMAIL;
- (BOOL)parse_CALURI;
- (BOOL)parse_BDAY;
- (BOOL)parse_ADR;
- (BOOL)parse_ADD;
- (BOOL)parseValueUsingSelector:(SEL)arg1;
- (BOOL)parseLine;
- (void)resetCachedParameters;
- (id)cachedParameterForName:(id)arg1;
- (id)people;
- (id)nextPersonWithLength:(long long *)arg1 addressBook:(id)arg2;
- (BOOL)importToValueSetter:(id)arg1;
- (BOOL)importToPerson:(id)arg1;
- (id)instantMessageServiceForString:(id)arg1;
- (void)parseBase64PhotoData:(id)arg1;
- (id)dateComponentsFromString:(id)arg1 omitYear:(long long)arg2;
- (BOOL)addIMValueTo:(id)arg1;
- (BOOL)addIMValueWithService:(id)arg1;
- (BOOL)parseABExtensionType:(id)arg1;
- (id)makeParameterWithLabel:(id)arg1 value:(id)arg2;
- (id)makeParameterWithValue:(id)arg1 forProperty:(id)arg2;
- (void)addParameterWithAddress:(id)arg1;
- (id)phoneLabel;
- (id)parseURLValue;
- (id)fallbackLabelForProperty:(id)arg1;
- (id)genericLabelForProperty:(id)arg1;
- (id)parseUnknownValueStartingAtPosition:(unsigned long long)arg1;
- (id)parseRemainingLine;
- (id)parseSingleValue;
- (id)firstValueForKey:(id)arg1 inExtension:(id)arg2;
- (void)addSocialProfileMultiValues;
- (void)addInstantMessageMultiValues;
- (void)addAddressMultiValues;
- (void)addMultiValues:(id)arg1 toProperty:(id)arg2;
- (void)cleanUpCardState;
- (BOOL)hasImportErrors;
- (void)dealloc;
- (id)initWithData:(id)arg1;

@end

