//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ABvCardLine.h"

@class NSString;

@protocol ABvCardParameterLine <ABvCardLine>
- (void)serializeValueWithStrategy:(id <ABvCardLineSerialization>)arg1;
- (BOOL)canSerializeWithStrategy:(id <ABvCardLineSerialization>)arg1;
- (void)addGroupedLine:(id <ABvCardLine>)arg1 withCounter:(long long *)arg2;
- (void)insertParameterWithName:(NSString *)arg1 value:(NSString *)arg2 atIndex:(unsigned long long)arg3;
- (void)addParameterWithName:(NSString *)arg1 value:(NSString *)arg2;
@end

