//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AOSFMMAccountInfo, NSData, NSString;

@protocol AOSNotificationOSXActions <NSObject>
- (oneway void)retrieveFMMAccountUsingCallback:(void (^)(AOSFMMAccountInfo *, NSError *))arg1;
- (oneway void)removeFMMAccountWithUsername:(NSString *)arg1 withAuthData:(NSData *)arg2 usingCallback:(void (^)(NSError *))arg3;
- (oneway void)addFMMAccount:(AOSFMMAccountInfo *)arg1 withAuthData:(NSData *)arg2 usingCallback:(void (^)(NSError *))arg3;
@end

