//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLock, NSString;

@interface AOSThreadManager : NSObject
{
    NSString *AOSKVerifyAccount;
    NSLock *_proxyLock;
}

+ (id)sharedManager;
+ (void)initialize;
- (void)AOSKUpdateAccountProperties:(id)arg1;
- (void)AOSKVerifyQuota:(id)arg1;
- (id)_createDictionaryFromAlias:(id)arg1;
- (id)_aliasesFromXMLData:(id)arg1;
- (id)_mailPrefsDataFromDict:(id)arg1;
- (id)_aliasInfoFromJSONData:(id)arg1;
- (void)AOSKPersistMailAliases:(id)arg1;
- (void)AOSKPersistMailProperties:(id)arg1;
- (id)_updateDerivedInfoUsingOldInfo:(id)arg1 andNewInfo:(id)arg2 forAccount:(struct AOSAccount *)arg3;
- (void)runStorageAlertThreadWithContext:(id)arg1;
- (void)AOSKPersistExpirationDate:(id)arg1;
- (BOOL)AOSKPersistFullUsername;
- (id)_generateSignUpSessionInfoForClient:(id)arg1;
- (void)runQuotaUsageThreadWithContext:(id)arg1;
- (void)runInitiateVettingThreadWithContext:(id)arg1;
- (void)AOSKPersistAccountData:(id)arg1;
- (void)runDataclassConfigThreadWithContext:(id)arg1;
- (void)runSystemCheckThreadWithContext:(id)arg1;
- (void)runConfigQueryThreadWithContext:(id)arg1;
- (void)runBuddyHelpThreadWithContext:(id)arg1;
- (void)runBuddyLoginThreadWithContext:(id)arg1;
- (void)runAppLoginThreadWithContext:(id)arg1;
- (void)runEmailLookupThreadWithContext:(id)arg1;
- (void)AOSKPersistAccountAttributes:(id)arg1;
- (void)AOSKPersistEmailAliasURL:(id)arg1;
- (id)_cachedSignUpSessionInfo;
- (void)_setCachedSignUpSessionInfo:(id)arg1;
- (void)clearCaches;
- (void)dealloc;
- (id)init;

@end

