//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BU_GVInterpolator;

__attribute__((visibility("hidden")))
@interface BU_VortexGL : NSObject
{
    struct _CGLContextObject *fDrawContext;
    struct _CGLContextObject *fBufferContext;
    struct _CGLPBufferObject *fPixelBuffer;
    struct _CGLPBufferObject *fPixelBuffer2;
    struct _CGLContextObject *fSharedContext;
    struct CGRect fViewport;
    unsigned long long fNumClouds;
    BOOL fWasEnabled;
    int fSaveUnit;
    int fSaveName;
    double fTime;
    unsigned long long fFrames;
    double fSpeed;
    double fTimeInput0;
    double fTimeInput1;
    double fTimeOutput0;
    double fTimeOutput1;
    BOOL fOutput0Defined;
    BOOL fOutput1Defined;
    double flfoPeriod;
    double flfoAmplitude;
    double flfoPhase;
    double flfoOffset;
    double fRadius;
    double fPower;
    double fRadians;
    double fFade;
    unsigned int fCloudTexture;
    unsigned int fBufferTexture;
    unsigned int fVortexTexture;
    BU_GVInterpolator *fPosX;
    BU_GVInterpolator *fPosY;
    BU_GVInterpolator *fPosZ;
    BU_GVInterpolator *fAlpha;
    BU_GVInterpolator *fWidth;
    BU_GVInterpolator *fInt1;
    BU_GVInterpolator *fInt2;
    void *fProgramObject;
    BOOL _cacheReady;
    struct _CGLContextObject *fVortexCacheContext;
    struct _CGLPBufferObject *fVortexCacheBuffer;
    void *fRemapCacheProgramObject;
    unsigned int fVortexCacheTexture;
    int fCurGLVirtualScreen;
}

+ (BOOL)isCompliantWithHardwareCapabilities;
- (id).cxx_construct;
- (void)_unsetTextureOnContext:(struct _CGLContextObject *)arg1 texture:(unsigned int)arg2 unitName:(unsigned int)arg3;
- (void)_setTextureOnContext:(struct _CGLContextObject *)arg1 texture:(unsigned int)arg2 unitName:(unsigned int)arg3;
- (BOOL)_uploadTexture:(void *)arg1 size:(struct CGSize)arg2 texture:(unsigned int)arg3 context:(struct _CGLContextObject *)arg4;
- (double)_LFOTime:(double)arg1;
- (void)renderAtTime:(double)arg1;
- (void)drawVortex;
- (void)drawCachedVortex;
- (unsigned int)vortexTexture;
- (void)setFade:(double)arg1;
- (void)setRadius:(double)arg1;
- (void)setPower:(double)arg1;
- (void)setRadians:(double)arg1;
- (void)setSpeed:(double)arg1;
- (void)dealloc;
- (void)cleanup:(struct _CGLContextObject *)arg1;
- (id)initWithFrame:(struct CGRect)arg1 context:(struct _CGLContextObject *)arg2 pixelFormat:(struct _CGLPixelFormatObject *)arg3 inputs:(id)arg4 cglError:(int *)arg5 glError:(unsigned int *)arg6;
- (void *)_createGLSLProgramWithVertexShader:(id)arg1 fragmentShader:(id)arg2 inputValues:(id)arg3;
- (void)_setTargetTexture:(unsigned int)arg1 onContext:(struct _CGLContextObject *)arg2 forPbuffer:(struct _CGLPBufferObject *)arg3 cglError:(int *)arg4 glError:(unsigned int *)arg5;
- (void)_configureViewportForContext:(struct _CGLContextObject *)arg1 withFrame:(struct CGRect)arg2 useOrthoProjection:(BOOL)arg3 cglError:(int *)arg4 glError:(unsigned int *)arg5;
- (int)_setupPbufferWithSharedContext:(struct _CGLContextObject *)arg1 pixelFormat:(struct _CGLPixelFormatObject *)arg2 size:(struct CGSize)arg3 pbuffer:(struct _CGLPBufferObject **)arg4 pbufferContext:(struct _CGLContextObject **)arg5;
- (void)_initInterpolators;

@end

