//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <QuartzCore/CAAnimation.h>

@interface CAAnimation (NSAnimationContextCommitHandler)

// Remaining properties
@property(copy, getter=NSAnimationContext_handler, setter=NSAnimationContext_setHandler:) CDUnknownBlockType NSAnimationContext_handler; // @dynamic NSAnimationContext_handler;
@end

