//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CNDDScanner;

__attribute__((visibility("hidden")))
@interface CNAddressDetector : NSObject
{
    CNDDScanner *_scanner;
}

+ (id)detector;
- (id)firstAddressInString:(id)arg1;
- (void)dealloc;
- (id)init;

@end

