//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface CSPaginatedResult : NSObject
{
    NSString *guid;
    NSNumber *startIndex;
    NSArray *results;
    NSNumber *total;
}

+ (void)initialize;
@property(retain) NSNumber *total; // @synthesize total;
@property(retain) NSArray *results; // @synthesize results;
@property(retain) NSNumber *startIndex; // @synthesize startIndex;
@property(retain) NSString *guid; // @synthesize guid;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

