//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreUI/CUIPSDLayerBaseRef.h>

__attribute__((visibility("hidden")))
@interface CUIPSDLayerRef : CUIPSDLayerBaseRef
{
}

- (id)gradient;
- (id)fillSample;
- (id)maskFromSlice:(unsigned int)arg1;
- (id)patternFromSlice:(unsigned int)arg1 isZeroSizeImage:(char *)arg2;
- (id)patternFromSlice:(unsigned int)arg1;
- (id)imageFromSlice:(unsigned int)arg1 isEmptyImage:(char *)arg2;
- (id)imageFromSlice:(unsigned int)arg1;
- (id)imageIsZeroSizeImage:(char *)arg1;
- (id)image;
- (struct CGImage *)createCGImage;
- (void)dealloc;
- (id)initWithImageRef:(id)arg1 layerIndex:(unsigned int)arg2;

@end

