//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface DDBinderInfo : NSObject <NSCoding>
{
    NSString *_name;
    long long _score;
    id _value;
    int _valueType;
    BOOL _NLPToken;
    BOOL _topLevel;
}

@property BOOL topLevel; // @synthesize topLevel=_topLevel;
- (id)description;
- (BOOL)isDummy;
- (void)setNLPToken:(BOOL)arg1;
- (BOOL)NLPToken;
- (void)setValueType:(int)arg1;
- (int)valueType;
- (void)setValue:(id)arg1;
- (id)value;
- (void)setScore:(long long)arg1;
- (long long)score;
- (id)name;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1;
- (id)monxmlAttributes;

@end

