//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding.h"

@class DDBinderInfo, DDGrammar, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface DDNonTerminal : NSObject <NSCoding>
{
    NSMutableArray *_productions;
    DDBinderInfo *_info;
    NSString *_name;
    long long _nonTerminalID;
    DDGrammar *_grammar;
    BOOL _matchesEpsilon;
    BOOL _skippable;
    BOOL _forceNonSkippable;
    struct __DDIndexSet *_followSet;
}

@property BOOL forceNonSkippable; // @synthesize forceNonSkippable=_forceNonSkippable;
@property BOOL skippable; // @synthesize skippable=_skippable;
@property BOOL matchesEpsilon; // @synthesize matchesEpsilon=_matchesEpsilon;
@property(copy) NSString *name; // @synthesize name=_name;
- (void)appendLocationDescription:(id)arg1 withIndexRef:(long long *)arg2;
- (void)appendDescription:(id)arg1 withIndexRef:(long long *)arg2;
- (void)setBinderInfo:(id)arg1;
- (id)binderInfo;
- (id)productions;
- (void)setProductions:(id)arg1;
- (id)asSymbols;
- (void)addProductionWithSymbols:(id)arg1 location:(id)arg2;
- (void)_reallyAddProductionWithSymbols:(id)arg1 location:(id)arg2;
- (id)description;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1 inGrammar:(id)arg2;
- (id)init;

@end

