//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DataDetectorsCore/DDAtomicRegexp.h>

@interface DDTokenRegexp : DDAtomicRegexp
{
}

- (long long)token;
- (int)splitRegexpWithDelegate:(id)arg1 owner:(id)arg2;
- (id)initWithTokenId:(long long)arg1;
- (id)symbolsInGrammar:(id)arg1 container:(id)arg2 withManager:(id)arg3;

@end

