//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class DDBasicHighlightsView, NSArray, NSMapTable, NSMutableArray, NSMutableSet;

__attribute__((visibility("hidden")))
@interface DDWK2Overlay : NSObject
{
    struct OpaqueWKBundlePageOverlay *_overlay;
    struct OpaqueWKBundlePage *_clientPage;
    id <DDHighlightsDelegate> _delegate;
    id <DDHighlightsDataSource> _dataSource;
    NSArray *_highlightedObjects;
    NSMapTable *_objectsToArrowlessViewMapping;
    NSMutableArray *_highlightQueue;
    NSMutableArray *_subviews;
    NSMutableSet *_trackingAreas;
    NSMutableSet *_enteredTrackingAreas;
    DDBasicHighlightsView *_clickedView;
    struct CGAffineTransform _transform;
    struct CGRect _visibleRect;
    BOOL _alwaysShowHighlights;
    BOOL _relayoutInProgress;
    BOOL _needsLayout;
}

@property(retain) DDBasicHighlightsView *clickedView; // @synthesize clickedView=_clickedView;
@property(retain) NSMutableSet *enteredTrackingAreas; // @synthesize enteredTrackingAreas=_enteredTrackingAreas;
@property(retain) NSMutableSet *trackingAreas; // @synthesize trackingAreas=_trackingAreas;
@property(retain) NSMutableArray *subviews; // @synthesize subviews=_subviews;
@property id <DDHighlightsDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property id delegate; // @synthesize delegate=_delegate;
- (BOOL)accessibilityShowDataDetectorMenuAtPoint:(struct CGPoint)arg1;
- (id)accessibilityDataDetectorTypeAtPoint:(struct CGPoint)arg1;
- (BOOL)accessibilityDataDetectorExistsAtPoint:(struct CGPoint)arg1;
- (void)removeTrackingArea:(id)arg1;
- (void)addTrackingArea:(id)arg1 alreadyInside:(BOOL)arg2;
- (void)removeAllTrackingAreas;
- (void)switchOffHighlights;
- (void)addSubview:(id)arg1;
- (void)updateHighlightStatesForMousePosition;
- (_Bool)mouseDraggedTo:(struct WKPoint)arg1 button:(int)arg2;
- (_Bool)mouseMovedTo:(struct WKPoint)arg1;
- (void)mouseExited:(id)arg1 location:(struct CGPoint)arg2;
- (void)mouseEntered:(id)arg1;
- (void)_mouseExitedBasicHLView:(id)arg1 withInfos:(id)arg2;
- (void)_mouseEnteredBasicHLView:(id)arg1 withRelatedObjects:(id)arg2;
- (void)setState:(int)arg1 forHighlightView:(id)arg2 disableAnimation:(BOOL)arg3;
- (_Bool)mouseUpAt:(struct WKPoint)arg1 button:(int)arg2;
- (_Bool)mouseDownAt:(struct WKPoint)arg1 button:(int)arg2;
- (void)handleMouseClick:(BOOL)arg1 onTriangle:(BOOL)arg2 onView:(id)arg3;
- (void)drawDirtyRect:(struct WKRect)arg1 inContext:(void *)arg2;
- (void)didMoveToPage:(struct OpaqueWKBundlePage *)arg1;
- (void)willMoveToPage:(struct OpaqueWKBundlePage *)arg1;
- (void)_addMultiViewForObject:(id)arg1 withArrow:(BOOL)arg2 availableViews:(id)arg3;
- (void)_setTrackingAreaForBasicHighlight:(id)arg1 entering:(BOOL)arg2 ignoreCleanup:(BOOL)arg3;
- (void)recomputeLayout;
- (void)hideHighlights;
- (void)reloadHighlights;
- (void)removeHighlights;
- (void)setAlwaysShowHighlights:(BOOL)arg1;
- (void)setHighlightedObjects:(id)arg1;
- (void)setAllState:(int)arg1 disableAnimations:(BOOL)arg2;
- (void)setNeedsRelayout;
- (void)deactivate;
- (void)installInPage:(struct OpaqueWKBundlePage *)arg1;
- (void)dealloc;
- (id)init;

@end

