//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <WebCore/DOMObject.h>

@class DOMDocument;

@interface DOMAbstractView : DOMObject
{
}

@property(readonly) DOMDocument *document;
- (void)dealloc;
- (void)_disconnectFrame;

@end

