//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <WebCore/DOMObject.h>

@class NSString;

@interface DOMCSSValue : DOMObject
{
}

@property(readonly) unsigned short cssValueType;
@property(copy) NSString *cssText;
- (void)finalize;
- (void)dealloc;

@end

