//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <WebCore/DOMHTMLElement.h>

@class NSString;

@interface DOMHTMLBodyElement : DOMHTMLElement
{
}

@property(copy) NSString *vLink;
@property(copy) NSString *text;
@property(copy) NSString *link;
@property(copy) NSString *bgColor;
@property(copy) NSString *background;
@property(copy) NSString *aLink;

@end

