//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <WebCore/DOMHTMLElement.h>

@class DOMHTMLFormElement, NSString;

@interface DOMHTMLLegendElement : DOMHTMLElement
{
}

@property(copy) NSString *accessKey;
@property(copy) NSString *align;
@property(readonly) DOMHTMLFormElement *form;

@end

