//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <WebCore/DOMHTMLElement.h>

@class NSString;

@interface DOMHTMLEmbedElement : DOMHTMLElement
{
}

@property int width;
@property(copy) NSString *type;
@property(copy) NSString *src;
@property(copy) NSString *name;
@property int height;
@property(copy) NSString *align;

@end

