//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <WebCore/DOMHTMLElement.h>

@class DOMStyleSheet, NSString;

@interface DOMHTMLStyleElement : DOMHTMLElement
{
}

@property(readonly) DOMStyleSheet *sheet;
@property(copy) NSString *type;
@property(copy) NSString *media;
@property BOOL disabled;

@end

