//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DiscRecording/DRFSObject.h>

@interface DRFolder : DRFSObject
{
}

+ (id)folderWithPath:(id)arg1;
+ (void)initialize;
+ (id)virtualFolderWithName:(id)arg1;
- (unsigned long long)_cfTypeID;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)finalize;
- (void)dealloc;
- (id)initWithPath:(id)arg1;
- (id)init;
- (id)children;
- (unsigned long long)count;
- (void)removeChild:(id)arg1;
- (void)addChild:(id)arg1;
- (void)makeVirtual;
- (id)initWithName:(id)arg1;
- (struct DRFolderObject *)_obj;
- (id)initWithFSRef:(const struct FSRef *)arg1;
- (void)removeObjectFromChildrenAtIndex:(unsigned int)arg1;
- (void)insertObject:(id)arg1 inChildrenAtIndex:(unsigned int)arg2;

@end

