//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface DSMMetaQueries : NSObject
{
}

+ (id)nodeForUUID:(id)arg1 inDocSet:(id)arg2;
- (id)tokenForAppleRef:(id)arg1;
- (id)tokenForAppleRef:(id)arg1 platform:(id)arg2 sdkVersion:(id)arg3;
- (id)reverseArray:(id)arg1;
- (id)_normalizedFamilyIdentifier:(id)arg1;
- (id)bestDocSetRecordsForPlatformName:(id)arg1 sdkVersion:(id)arg2 searchDocSetRecords:(id)arg3 includeMismatchedFamilyNames:(BOOL)arg4 includeMismatchedVersions:(BOOL)arg5;
- (id)urlForUUID:(id)arg1 inDocSet:(id)arg2;
- (id)tokensForSymbol:(id)arg1 platform:(id)arg2 sdkVersion:(id)arg3 useFallbackNameSearch:(BOOL)arg4;

@end

