//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DTGraphKit/DTBarGraph.h>

@class DTNetworkGraphObject, NSArray;

@interface DTNetworkGraph : DTBarGraph
{
    struct CGRect _contentBox;
    NSArray *nodes;
    NSArray *edges;
    DTNetworkGraphObject *selectedObject;
    id <DTNetworkGraphLayout> layout;
}

@property(retain) DTNetworkGraphObject *selectedObject; // @synthesize selectedObject;
@property(retain) NSArray *edges; // @synthesize edges;
@property(retain) NSArray *nodes; // @synthesize nodes;
- (void)mouseDown:(id)arg1;
@property(retain) id <DTNetworkGraphLayout> layout; // @synthesize layout;
- (void)observeModel:(BOOL)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)resetPaths;
- (void)createNodesAndEdges;
- (void)drawXAxis:(struct CGRect)arg1;
- (void)drawYAxis:(struct CGRect)arg1;
- (void)drawContent:(struct CGRect)arg1;
- (void)drawBorder:(struct CGRect)arg1;
- (double)calculateVerticalBorderBuffer;
- (double)calculateHorizontalBorderBuffer;
- (void)dealloc;
- (id)init;

@end

