//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTFoundation/DVTCollectCertificateFailuresOperation.h>

@interface DVTCollectCertificateFailuresOperation (UIExtensions)
+ (id)_UIOperationWithToken:(id)arg1;
@end

