//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DVTInvalidation.h"

@class DVTAbstractLibraryGroup, DVTExtension, DVTLibraryController, DVTStackBacktrace, NSArray, NSDictionary, NSImage, NSMutableArray, NSMutableDictionary, NSString;

@interface DVTLibrary : NSObject <DVTInvalidation>
{
    NSMutableDictionary *_librarySourceGroupsByLibrarySourceID;
    NSMutableArray *_orderedLibrarySourceIdentifiers;
    NSMutableDictionary *_identifiedAssets;
    NSString *_identifier;
    DVTExtension *_representedExtension;
    NSArray *_detailControllerIdentifiers;
    CDUnknownBlockType _groupComparator;
    DVTLibraryController *_libraryController;
    DVTAbstractLibraryGroup *_rootGroup;
    DVTAbstractLibraryGroup *_everythingGroup;
}

+ (void)initialize;
@property(readonly) DVTAbstractLibraryGroup *everythingGroup; // @synthesize everythingGroup=_everythingGroup;
@property(readonly) DVTAbstractLibraryGroup *rootGroup; // @synthesize rootGroup=_rootGroup;
@property(readonly) NSDictionary *identifiedAssets; // @synthesize identifiedAssets=_identifiedAssets;
@property(retain) DVTLibraryController *libraryController; // @synthesize libraryController=_libraryController;
@property(retain, nonatomic) NSArray *orderedLibrarySourceIdentifiers; // @synthesize orderedLibrarySourceIdentifiers=_orderedLibrarySourceIdentifiers;
@property(copy, nonatomic) CDUnknownBlockType groupComparator; // @synthesize groupComparator=_groupComparator;
@property(copy, nonatomic) NSArray *detailControllerIdentifiers; // @synthesize detailControllerIdentifiers=_detailControllerIdentifiers;
@property(readonly) DVTExtension *representedExtension; // @synthesize representedExtension=_representedExtension;
@property(readonly) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)removeAllAssets;
- (void)removeAsset:(id)arg1;
- (void)addAsset:(id)arg1 toLibrarySourceWithIdentifier:(id)arg2 subpath:(id)arg3;
- (id)assetWithIdentifier:(id)arg1;
- (BOOL)containsAssetWithIdentifier:(id)arg1;
- (id)assets;
- (id)groupWithDisplayPath:(id)arg1 fromGroup:(id)arg2 create:(BOOL)arg3;
- (void)setImage:(id)arg1 forLibrarySourceWithIdentifier:(id)arg2 subpath:(id)arg3;
- (void)setTitle:(id)arg1 forLibrarySourceWithIdentifier:(id)arg2;
- (void)removeSubpath:(id)arg1 fromLibrarySourceWithIdentifier:(id)arg2;
- (void)removeLibrarySourceWithIdentifier:(id)arg1;
- (void)addLibrarySourceWithIdentifier:(id)arg1 andTitle:(id)arg2;
- (void)insertLibrarySourceWithIdentifier:(id)arg1 andTitle:(id)arg2 atIndex:(long long)arg3;
- (BOOL)containsLibrarySourceWithIdentifier:(id)arg1;
- (id)libraryGroupForLibrarySourceWithIdentifier:(id)arg1;
@property(copy) NSString *title;
@property(retain) NSImage *image;
- (void)loadDetailControllerIdentifiersFromExtension;
- (void)loadAssetsFromExtension;
- (id)effectiveSubpathsForAsset:(id)arg1;
- (id)effectiveLibrarySourceIdentifierForAsset:(id)arg1;
- (void)loadLibrarySourcesFromExtension;
- (id)assetExtensionsForLibrary;
- (void)addObserver:(id)arg1 forKeyPath:(id)arg2 options:(unsigned long long)arg3 context:(void *)arg4;
- (void)primitiveInvalidate;
- (id)initWithExtension:(id)arg1 andLibraryController:(id)arg2;
- (id)initWithIdentifier:(id)arg1 andTitle:(id)arg2;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

