//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSWindow;

@interface DVTScaleInWindowAnimator : NSObject
{
    NSWindow *_windowToScaleIn;
    struct CGPoint _pointToScaleFrom;
    double _finalAlpha;
    NSWindow *_animationWindow;
}

+ (void)scaleInWindow:(id)arg1 fromPoint:(struct CGPoint)arg2 finalAlpha:(double)arg3;
+ (void)scaleInWindow:(id)arg1 fromPoint:(struct CGPoint)arg2;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (id)_createFadeInAnimation;
- (id)_createScaleInAnimation;
- (id)_createScaleInAndFadeInAnimation;
- (void)_scaleInWindow;
- (struct CATransform3D)_transformForScale:(double)arg1;
- (id)_initWithWindow:(id)arg1 point:(struct CGPoint)arg2 finalAlpha:(double)arg3;

@end

