//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTKit/DVTAnnotationProvider.h>

@class DVTDiffDescriptor, DVTDiffSession, DVTMapTable, DVTObservingToken, NSURL;

@interface DVTSourceCodeComparisonAnnotationProvider : DVTAnnotationProvider
{
    NSURL *_documentURL;
    int _dataSourceType;
    DVTDiffSession *_diffSession;
    DVTDiffDescriptor *_diffDescriptor;
    DVTObservingToken *_observingToken;
    DVTObservingToken *_selectionToken;
    DVTObservingToken *_disabledToken;
    DVTObservingToken *_diffDescriptorsShouldAppearAsUnfocusedToken;
    DVTObservingToken *_diffDescriptorsShouldAppearAsInactive;
    DVTMapTable *_diffDescriptorToAnnotation;
    id _themeObserver;
}

+ (id)annotationProviderForContext:(id)arg1 error:(id *)arg2;
@property(retain) DVTObservingToken *diffDescriptorsShouldAppearAsInactiveToken; // @synthesize diffDescriptorsShouldAppearAsInactiveToken=_diffDescriptorsShouldAppearAsInactive;
@property(retain) DVTObservingToken *diffDescriptorsShouldAppearAsUnfocusedToken; // @synthesize diffDescriptorsShouldAppearAsUnfocusedToken=_diffDescriptorsShouldAppearAsUnfocusedToken;
@property(retain) DVTObservingToken *disabledToken; // @synthesize disabledToken=_disabledToken;
@property(retain) DVTObservingToken *selectionToken; // @synthesize selectionToken=_selectionToken;
@property(retain) DVTObservingToken *observingToken; // @synthesize observingToken=_observingToken;
@property(retain) DVTDiffDescriptor *diffDescriptor; // @synthesize diffDescriptor=_diffDescriptor;
@property(retain) DVTDiffSession *diffSession; // @synthesize diffSession=_diffSession;
@property int dataSourceType; // @synthesize dataSourceType=_dataSourceType;
@property(retain) NSURL *documentURL; // @synthesize documentURL=_documentURL;
- (void).cxx_destruct;
- (void)providerWillUninstall;
- (id)_addAnnotationForDiffDescriptor:(id)arg1;
- (id)initWithContext:(id)arg1;

@end

