//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IDEActivityLogSection, NSString;

@interface IDEBotExecutionActivityLog : NSObject
{
    NSString *_title;
    IDEActivityLogSection *_log;
}

@property(readonly) IDEActivityLogSection *log; // @synthesize log=_log;
@property(readonly, copy) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 log:(id)arg2;

@end

