//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEKit/IDEBatchFindLocationPickerItem.h>

@class NSString;

@interface IDEBatchFindLocationPickerSchemeItem : IDEBatchFindLocationPickerItem
{
    int _type;
    NSString *_uuid;
}

@property(retain) NSString *uuid; // @synthesize uuid=_uuid;
@property int type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

