//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEFoundation/IDEIndexCollection.h>

@class DVTSourceCodeSymbolKind;

@interface IDEIndexAutoImportItemCollection : IDEIndexCollection
{
    DVTSourceCodeSymbolKind *_symbolKind;
}

@property(retain, nonatomic) DVTSourceCodeSymbolKind *symbolKind; // @synthesize symbolKind=_symbolKind;
- (void).cxx_destruct;
- (id)instantiateRow:(struct sqlite3_stmt *)arg1;
- (id)tempTableSchema;

@end

