//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class DVTTextViewWithPlaceholder, IDEWorkspace, NSString, NSWindow;

@interface IDENewSnapshotWindowController : NSWindowController
{
    NSString *_snapshotName;
    NSString *_snapshotDescription;
    DVTTextViewWithPlaceholder *_descriptionTextView;
    IDEWorkspace *_workspace;
    IDENewSnapshotWindowController *_wc;
    NSWindow *_hostWindow;
}

+ (void)runSheetForWindow:(id)arg1;
@property(copy) NSString *snapshotDescription; // @synthesize snapshotDescription=_snapshotDescription;
@property(copy) NSString *snapshotName; // @synthesize snapshotName=_snapshotName;
- (void).cxx_destruct;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)sheetOKAction:(id)arg1;
- (void)sheetCancelAction:(id)arg1;
- (void)_beginSheetForWindow:(id)arg1;
- (id)windowNibName;

@end

