//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEKit/IDEViewController.h>

#import "DVTReplacementViewDelegate.h"
#import "DVTStatefulObject.h"
#import "IDENavigatorOutlineViewLoadingDelegate.h"

@class DVTBorderedView, DVTChooserView, DVTExtension, DVTObservingToken, DVTReplacementView, DVTStateToken, IDENavigatorFilterControlBar, NSArrayController, NSMutableDictionary, NSString;

@interface IDENavigatorArea : IDEViewController <IDENavigatorOutlineViewLoadingDelegate, DVTReplacementViewDelegate, DVTStatefulObject>
{
    DVTChooserView *_chooserView;
    DVTBorderedView *_borderedView;
    DVTReplacementView *_replacementView;
    DVTBorderedView *_filterControlBarBorderedView;
    NSArrayController *_extensionsController;
    DVTExtension *_currentExtension;
    NSMutableDictionary *_perNavigatorCache;
    NSString *_nonMiniDebuggingModeExtensionIdentifier;
    DVTObservingToken *_workspaceActivityObservingToken;
    DVTObservingToken *_inMiniDebuggingModeObservingToken;
    BOOL _didLoadInitialNavigator;
    BOOL _isInvalidating;
    IDENavigatorFilterControlBar *_filterControlBar;
}

+ (long long)version;
+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (id)keyPathsForValuesAffectingCurrentNavigator;
+ (id)navigatorsForContext:(id)arg1;
@property(readonly) IDENavigatorFilterControlBar *filterControlBar; // @synthesize filterControlBar=_filterControlBar;
@property(retain, nonatomic) DVTExtension *currentExtension; // @synthesize currentExtension=_currentExtension;
@property(retain) NSArrayController *extensionsController; // @synthesize extensionsController=_extensionsController;
- (void).cxx_destruct;
- (double)minimumContentWidth;
- (void)commitStateToDictionary:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
- (void)_setCurrentExtensionIdentifier:(id)arg1;
- (id)_currentExtensionIdentifier;
- (BOOL)delegateFirstResponder;
- (void)_inMiniDebuggingModeChanged;
- (id)currentNavigator;
- (void)_clearPerNavigatorCache;
- (void)_cancelWorkspaceActivityObserving;
- (void)showNavigatorWithIdentifier:(id)arg1;
- (void)viewWillUninstall;
- (void)viewDidInstall;
- (void)outlineViewDidDrawInitialContent:(id)arg1;
- (void)outlineViewWillDrawInitialContent:(id)arg1;
- (void)replacementView:(id)arg1 didInstallViewController:(id)arg2;
- (void)replacementView:(id)arg1 willInstallViewController:(id)arg2;
- (void)replacementView:(id)arg1 willCloseViewController:(id)arg2;
- (id)perNavigatorCacheKeyForNavigator:(id)arg1;
- (void)activateFilterFieldForFocus;
- (void)installFilterControlBarForNavigator:(id)arg1;
- (void)primitiveInvalidate;
- (void)loadView;
- (id)supportedContext;

// Remaining properties
@property(retain) DVTStateToken *stateToken; // @dynamic stateToken;

@end

