//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEFoundation/IDEAlertEvent.h>

@interface IDERunGeneratesOutputAlertEvent : IDEAlertEvent
{
}

- (void)runInWorkspace:(id)arg1 context:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;

@end

