//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEKit/IDERunSheetPhaseModel.h>

@interface IDERunSheetProfilePhaseModel : IDERunSheetPhaseModel
{
}

+ (id)keyPathsForValuesAffectingNavigableItem_name;
- (id)schemeCommandTitle;
- (int)schemePhaseModelCommand;
- (id)navigableItem_image;
- (id)navigableItem_name;
- (Class)detailViewControllerClass;
- (id)runPhase;

@end

