//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEKit/IDERunSheetSubphaseModel.h>

@interface IDERunSheetPrimarySubphaseModel : IDERunSheetSubphaseModel
{
}

+ (id)keyPathsForValuesAffectingNavigableItem_name;
- (BOOL)navigableItem_hasWork;
- (id)navigableItem_name;
- (Class)detailViewControllerClass;

@end

