//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import "IDEReviewFilesViewControllerDelegate.h"
#import "NSLayoutManagerDelegate.h"
#import "NSSplitViewDelegate.h"

@class DVTBorderedView, DVTObservingToken, IDENavigableItemCoordinator, IDEReviewFilesViewController, IDESourceControlCommitViewerComparisonEditorDataSource, IDESourceControlCommitViewerNavigatorDataSource, IDESourceControlLogItem, IDESourceControlRepository, IDESourceControlTreeItem, NSArray, NSSplitView, NSString, NSTextView;

@interface IDESourceControlCommitViewerWindowController : NSWindowController <NSSplitViewDelegate, IDEReviewFilesViewControllerDelegate, NSLayoutManagerDelegate>
{
    DVTBorderedView *_reviewFilesBorderedView;
    DVTBorderedView *_borderedView;
    NSSplitView *_splitView;
    NSTextView *_commitTextView;
    IDEReviewFilesViewController *_reviewFilesViewController;
    IDESourceControlTreeItem *_initialSelection;
    IDESourceControlCommitViewerNavigatorDataSource *_navigatorDataSource;
    IDENavigableItemCoordinator *_coordinator;
    IDESourceControlCommitViewerNavigatorDataSource *_fileSystemDataSource;
    IDESourceControlCommitViewerComparisonEditorDataSource *_comparisonEditorDataSource;
    IDESourceControlRepository *_repository;
    NSArray *_itemsWithStatus;
    IDESourceControlLogItem *_logItem;
    struct CGRect _commitMessageRect;
    double _commitMessageSplitMaxHeight;
    BOOL _initialSplitPositionHasHappened;
    DVTObservingToken *_comparisonEditorObservingToken;
    NSString *_startingRevision;
}

+ (void)runPreviewSheetForWindow:(id)arg1 viewingCommit:(id)arg2 onRepository:(id)arg3 itemsWithStatus:(id)arg4 withInitialSelection:(id)arg5 fromRevision:(id)arg6;
+ (void)runPreviewSheetForWindow:(id)arg1 viewingCommit:(id)arg2 onRepository:(id)arg3 itemsWithStatus:(id)arg4 withInitialSelection:(id)arg5;
@property(retain) NSString *startingRevision; // @synthesize startingRevision=_startingRevision;
@property(retain) IDESourceControlTreeItem *initialSelection; // @synthesize initialSelection=_initialSelection;
@property(retain) IDESourceControlLogItem *logItem; // @synthesize logItem=_logItem;
@property(retain) NSArray *itemsWithStatus; // @synthesize itemsWithStatus=_itemsWithStatus;
@property(retain) IDESourceControlRepository *repository; // @synthesize repository=_repository;
- (void).cxx_destruct;
- (BOOL)splitView:(id)arg1 shouldAdjustSizeOfSubview:(id)arg2;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)ok:(id)arg1;
- (void)willOpenDocumentLocation:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)lastRevisionOnRepository:(id)arg1 forAbsolutePath:(id)arg2 StartingWithRevision:(id)arg3 withCompletionBlock:(CDUnknownBlockType)arg4;
- (id)_temporaryFileLocationForRepository:(id)arg1 remoteAbsolutePath:(id)arg2 revisionNumber:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)_configureDataSources;
- (void)setInitialSelection:(id)arg1 forNavigatorOutlineView:(id)arg2;
- (id)treeItemFilterPredicate;
- (void)layoutManager:(id)arg1 didCompleteLayoutForTextContainer:(id)arg2 atEnd:(BOOL)arg3;
- (double)_positionOfSplitterWithCommitMessageRect:(struct CGRect)arg1;
- (void)_runSheetForWindow:(id)arg1;
- (id)windowNibName;

@end

