//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTKit/DVTViewController.h>

#import "IDESnapshotConfirmationDelegate.h"

@class DVTStackBacktrace, IDEWorkspace, NSImage, NSString, NSWindow;

@interface IDESnapshotAreYouSureController : DVTViewController <IDESnapshotConfirmationDelegate>
{
    NSWindow *_hostWindow;
    CDUnknownBlockType _completionBlock;
    IDEWorkspace *_workspace;
    NSWindow *_sheetWindow;
    NSImage *_snapshotImage;
    NSString *_projectOrWorkspaceCapitalized;
    NSString *_operationName;
    BOOL _shouldTakeSnapshot;
}

+ (id)defaultViewNibName;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)cleanup;
- (void)_sheetDidEnd;
- (void)skipSnapshot:(id)arg1;
- (void)takeSnapshot:(id)arg1;
- (id)messageDescription;
- (id)messageTitle;
- (void)requestSnapshotConfirmationForOperationName:(id)arg1 inWorkspace:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)initUsingDefaultNib;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

