//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTKit/DVTViewController.h>

#import "IDECompletionDestinationDelegate.h"

@class DVTNotificationToken, IDECompletionDestinationManager, IDEGroup, IDESaveDestinationContext, NSPopUpButton, NSView;

@interface IDESaveDestinationController : DVTViewController <IDECompletionDestinationDelegate>
{
    NSPopUpButton *_destinationPopUp;
    NSPopUpButton *_formatPopUp;
    NSView *_formatView;
    IDESaveDestinationContext *_context;
    CDUnknownBlockType _completionBlock;
    IDECompletionDestinationManager *_destinationManager;
    IDEGroup *_initialDestinationGroup;
    DVTNotificationToken *_panelDidOrderOutNotificationToken;
    BOOL _didFinish;
    BOOL _didOrderOut;
}

+ (id)assistantForContext:(id)arg1;
+ (Class)assistantClassForContext:(id)arg1;
@property(copy) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain) NSView *formatView; // @synthesize formatView=_formatView;
@property(retain) NSPopUpButton *formatPopUp; // @synthesize formatPopUp=_formatPopUp;
@property(retain) NSPopUpButton *destinationPopUp; // @synthesize destinationPopUp=_destinationPopUp;
@property(retain, nonatomic) IDESaveDestinationContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (id)targetWorkspacesForDestinationManager:(id)arg1;
- (void)destinationManagerWorkspaceDidChange:(id)arg1;
- (void)destinationManagerGroupDidChange:(id)arg1;
- (BOOL)destinationManager:(id)arg1 shouldAddItemToMenu:(id)arg2;
- (void)changeDestinationFormat:(id)arg1;
- (void)didFinishSaveSuccessfully:(BOOL)arg1;
- (void)begin;
- (id)configuredSavePanel;
- (void)primitiveInvalidate;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

