//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IDEKit/IDEKeyDrivenNavigableItem.h>

@class DVTObservingToken;

@interface IDESourceControlWorkingTreeItemHolderNavigableItem : IDEKeyDrivenNavigableItem
{
    DVTObservingToken *_childWrappersToken;
}

- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)initWithRepresentedObject:(id)arg1;

@end

