//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _IDSBatchIDQueryController;

@interface IDSBatchIDQueryController : NSObject
{
    _IDSBatchIDQueryController *_internal;
}

- (void)invalidate;
- (void)setDestinations:(id)arg1;
- (void)dealloc;
- (id)initWithService:(id)arg1 delegate:(id)arg2 queue:(struct dispatch_queue_s *)arg3;

@end

