//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface IMWeakArray : NSObject
{
    NSMutableArray *_weakArray;
}

- (id)copyMutableSet;
- (id)copyMutableArray;
- (void)removeObject:(id)arg1;
- (void)addObjectIfNotIdenticalObjectExists:(id)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)description;
- (void)addObject:(id)arg1;
- (void)dealloc;

@end

