//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <ISSupport/ISS_DAVMakeCollection.h>

@interface ISS_DMDAVMkcol : ISS_DAVMakeCollection
{
}

+ (id)mkcolRequestWithSession:(id)arg1 URI:(id)arg2 token:(id)arg3;
- (void)finalizeOperation;
- (id)initMkcolWithSession:(id)arg1 URI:(id)arg2 token:(id)arg3;

@end

