//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface MallocTotalDiff : NSObject
{
    long long totalBytesReclaimableDiff;
    long long totalNodesReclaimableDiff;
    long long totalBytesNonReclaimableDiff;
    long long totalNodesNonReclaimableDiff;
    NSMutableArray *purgeTypeTotalDiffs;
}

@property(retain) NSMutableArray *purgeTypeTotalDiffs; // @synthesize purgeTypeTotalDiffs;
@property long long totalNodesNonReclaimableDiff; // @synthesize totalNodesNonReclaimableDiff;
@property long long totalBytesNonReclaimableDiff; // @synthesize totalBytesNonReclaimableDiff;
@property long long totalNodesReclaimableDiff; // @synthesize totalNodesReclaimableDiff;
@property long long totalBytesReclaimableDiff; // @synthesize totalBytesReclaimableDiff;
- (void)printTotals:(id)arg1;
- (id)totalForPurgeType:(int)arg1;
- (void)dealloc;
- (id)initWithMallocTotalBefore:(id)arg1 After:(id)arg2;

@end

