//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSColorSpaceSliders.h>

@interface NSCMYKSliders : NSColorSpaceSliders
{
    id cyanSlider;
    id yellowSlider;
    id magentaSlider;
    id blackSlider;
    id cyanText;
    id yellowText;
    id magentaText;
    id blackText;
    id cmykView;
}

+ (id)genericColorSpace;
- (void)_adjustControls:(id)arg1 andSetColor:(BOOL)arg2;
- (void)adjustControls:(id)arg1;
- (BOOL)worksWhenModal;
- (void)viewSizeChanged:(id)arg1;
- (struct CGSize)requiredMinSize;
- (id)regularColorIfPossible:(id)arg1;
- (void)setMatchedColor:(id)arg1;
- (id)fieldEditableControl;
- (id)provideNewSubview:(id)arg1;

@end

