//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSCoder.h>

@interface NSCoder (ProThemeAdditions)
- (unsigned long long)decodeThemeForKey:(id)arg1;
- (unsigned long long)decodeTheme;
- (void)encodeTheme:(unsigned long long)arg1 forKey:(id)arg2;
- (void)encodeTheme:(unsigned long long)arg1;
@end

