//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSString;

@interface NSCustomView : NSView
{
    NSString *className;
    NSView *view;
    id extension;
}

+ (void)initialize;
- (void)setClassName:(id)arg1;
- (id)className;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)nibInstantiateWithObjectInstantiator:(id)arg1;
- (void)_setAsClipViewDocumentViewIfNeeded;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

