//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDocument, NSIndexSet;

@interface NSDocumentErrorRecoveryAttempter : NSObject
{
    NSDocument *_document;
    id _wrappedRecoveryAttempter;
    CDUnknownBlockType _continuerOrNil;
    long long _silentRecoveryOptionIndex;
    CDUnknownBlockType _docModalRecoveryAttempter;
    CDUnknownBlockType _appModalRecoveryAttempter;
    CDUnknownBlockType _recoveryCancelerOrNil;
    NSIndexSet *_customOptionIndexes;
}

- (void)cancelRecovery;
- (BOOL)attemptSilentRecoveryFromError:(id)arg1 error:(id *)arg2;
- (void)attemptSilentRecoveryFromError:(id)arg1 thenContinue:(CDUnknownBlockType)arg2;
- (BOOL)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2;
- (void)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2 delegate:(id)arg3 didRecoverSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (void)dealloc;
- (id)initWithDocument:(id)arg1 silentRecoveryOptionIndex:(unsigned long long)arg2 docModalRecoveryAttempter:(CDUnknownBlockType)arg3 appModalRecoveryAttempter:(CDUnknownBlockType)arg4 recoveryCanceler:(CDUnknownBlockType)arg5;
- (id)initWithDocument:(id)arg1 wrappedRecoveryAttempter:(id)arg2 customOptionIndexes:(id)arg3 docModalRecoveryAttempter:(CDUnknownBlockType)arg4 appModalRecoveryAttempter:(CDUnknownBlockType)arg5 recoveryCanceler:(CDUnknownBlockType)arg6;
- (id)initWithDocument:(id)arg1 wrappedRecoveryAttempter:(id)arg2 continuer:(CDUnknownBlockType)arg3;

@end

