//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding.h"
#import "NSCopying.h"

@class NSDictionary, NSString;

@interface NSException : NSObject <NSCopying, NSCoding>
{
    NSString *name;
    NSString *reason;
    NSDictionary *userInfo;
    id reserved;
}

+ (void)raise:(id)arg1 format:(id)arg2;
+ (void)raise:(id)arg1 format:(id)arg2 arguments:(struct __va_list_tag [1])arg3;
+ (id)exceptionWithName:(id)arg1 reason:(id)arg2 userInfo:(id)arg3;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithName:(id)arg1 reason:(id)arg2 userInfo:(id)arg3;
- (id)init;
- (void)raise;
- (id)description;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)_installStackTraceKeyIfNeeded;
- (id)callStackSymbols;
- (id)callStackReturnAddresses;
- (id)userInfo;
- (id)reason;
- (id)name;

@end

