//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSBox.h>

@class NSMutableArray, NSMutableDictionary;

@interface NSFontEffectsBox : NSBox
{
    id _blurSlider;
    id _opacitySlider;
    id _radiusSlider;
    id _angleDial;
    id _mainControlsBox;
    id _shadowControlsBox;
    id _dividerImage;
    id _mainEffectsBox;
    id _angleLabel;
    id _effectsPopup;
    id _underlineButton;
    id _strikeButton;
    id _topDividerLine;
    id _bottomDividerLine;
    id _shadowToggleButton;
    id _textColorButton;
    id _documentColorButton;
    NSMutableDictionary *_attributesToAdd;
    NSMutableArray *_attributesToRemove;
    id _febUnused[5];
    int _shadowBlur;
    int _colorState;
    struct __feblags {
        unsigned int showUnderline:1;
        unsigned int showStrikethrough:1;
        unsigned int showTextColor:1;
        unsigned int showDocumentColor:1;
        unsigned int showShadowEffects:1;
        unsigned int reserved:27;
    } _febFlags;
}

- (void)_validateShadowEffect:(BOOL)arg1;
- (void)_validateDocumentColor:(BOOL)arg1;
- (void)_validateTextColor:(BOOL)arg1;
- (void)_validateStrikethrough:(BOOL)arg1;
- (void)_validateUnderline:(BOOL)arg1;
- (void)_sendCarbonNotificationFor:(unsigned long long)arg1 tags:(const unsigned int *)arg2 withValuePtrs:(const void **)arg3 andSizes:(const unsigned long long *)arg4;
- (void)_sendCarbonNotificationForTag:(unsigned int)arg1 withValuePtr:(const void *)arg2 andSize:(unsigned long long)arg3;
- (void *)carbonNotificationProc;
- (void)_toggleShadow:(id)arg1;
- (void)_openEffectsButton:(id)arg1;
- (void)_setAttributes:(id)arg1 isMultiple:(BOOL)arg2;
- (id)convertAttributes:(id)arg1;
- (void)_orderFrontModalColorPanel;
- (void)_changeColorToColor:(id)arg1;
- (void)changeColor:(id)arg1;
- (void)frameDidChange:(id)arg1;
- (void)_changeShadowBlur:(id)arg1;
- (void)_changeShadowAngle:(id)arg1;
- (void)_changeShadowOpacity:(id)arg1;
- (void)_changeDocumentColor:(id)arg1;
- (void)_changeTextColor:(id)arg1;
- (void)awakeFromNib;

@end

