//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/NSScriptObjectSpecifier.h>

@interface NSIndexSpecifier : NSScriptObjectSpecifier
{
    long long _index;
}

+ (id)_containerAtIndex:(unsigned long long *)arg1 traversingBackward:(BOOL)arg2 inContainerTree:(id)arg3 ofDepth:(unsigned long long)arg4;
+ (BOOL)_fromContainerInfo:(const CDStruct_4cb9d06e *)arg1 andKeyCode:(unsigned int)arg2 getAdjustedContainerInfo:(CDStruct_4cb9d06e *)arg3 andKey:(id *)arg4;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (BOOL)_putKeyFormAndDataInRecord:(id)arg1;
- (id)_simpleDescription;
- (unsigned long long)_specifiedObjectTreeDepth;
- (id)_typeDescription;
- (id)_moreCompleteVariantOfTypeDescription:(id)arg1;
- (BOOL)_specifiesCollection;
- (BOOL)_specifiesMultipleIndexedObjectsPerContainer;
- (BOOL)_specifiesSingleIndexedObjectPerContainer;
- (unsigned long long)_specifiedIndexOfObjectInContainer:(id)arg1;
- (id)objectsByEvaluatingWithContainers:(id)arg1;
- (id)keyClassDescription;
- (long long)index;
- (void)setIndex:(long long)arg1;
- (id)_initFromRecord:(id)arg1;
- (id)initWithContainerClassDescription:(id)arg1 containerSpecifier:(id)arg2 key:(id)arg3 index:(long long)arg4;
- (id)initWithContainerClassDescription:(id)arg1 containerSpecifier:(id)arg2 key:(id)arg3;

@end

