//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSNavFileListDelegate.h>

@class NSArray, NSNavNode;

@interface NSNavNaughtDelegate : NSNavFileListDelegate
{
    NSNavNode *_currentDirectoryNode;
    NSArray *_selectedNodes;
}

- (void)_debug;
- (id)showNode:(id)arg1 inDirectory:(id)arg2 selectIfEnabled:(BOOL)arg3;
- (BOOL)canHighlightNode:(id)arg1;
- (id)selectedNodesIncludingDirectories;
- (id)selectedNodes;
- (void)_setSelectedNodes:(id)arg1;
- (void)sendSelectionChangedNotification;
- (void)setCurrentDirectoryNode:(id)arg1;
- (void)_setCurrentDirectoryNode:(id)arg1;
- (id)currentDirectoryNode;
- (id)visualRootNode;
- (void)reloadChildrenForNode:(id)arg1;
- (void)setCurrentBrowsingNodePath:(id)arg1;
- (void)loadAndRestoreCurrentBrowsingNodePath:(id)arg1 selectedNodes:(id)arg2;
- (void)dealloc;

@end

