//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSNavPreviewController.h>

@interface NSNavNodePreviewController : NSNavPreviewController
{
}

- (void)setRepresentedObject:(id)arg1;
- (void)_startObservingRepObject;
- (void)_stopObservingRepObject;
- (void)dealloc;

@end

