//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <CoreFoundation/NSNull.h>

@interface NSNull (NSScriptingInternalCommandHandling)
- (BOOL)_scriptingCanHandleCommand:(id)arg1;
- (BOOL)_scriptingMightHandleCommand:(id)arg1;
@end

