//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSSavePanel.h>

@interface NSOpenPanel : NSSavePanel
{
    char _reservedOpenPanel[4];
    void *_privateOpenPanel;
}

+ (id)openPanel;
- (void)newDocument:(id)arg1;
- (void)_dismissModalForTerminate;
- (BOOL)preventsApplicationTerminationWhenModal;
- (void)setCanChooseFiles:(BOOL)arg1;
- (BOOL)canChooseFiles;
- (void)setAllowsMultipleSelection:(BOOL)arg1;
- (BOOL)allowsMultipleSelection;
- (void)setCanChooseDirectories:(BOOL)arg1;
- (BOOL)canChooseDirectories;
- (void)setResolvesAliases:(BOOL)arg1;
- (BOOL)resolvesAliases;
- (id)filenames;
- (id)URLs;
- (void)_initSaveMode;
- (void)_unregisterKVOWithViewBridgeService:(id)arg1 onBridge:(id)arg2;
- (void)_registerKVOWithViewBridgeService:(id)arg1 onBridge:(id)arg2;

@end

