//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface NSPersistentUIBucket : NSObject
{
    NSMutableDictionary *state;
    NSMutableDictionary *publicProperties;
    BOOL contentsHaveInvalidState;
    NSString *frameString;
    unsigned int windowID;
    unsigned int windowNumber;
}

@property(copy) NSString *frameString; // @synthesize frameString;
@property(readonly) NSMutableDictionary *state; // @synthesize state;
- (void)dealloc;
- (BOOL)isMenuBar;
- (BOOL)isGlobal;
- (void)setPublicProperty:(id)arg1 forKey:(id)arg2;
- (void)encodeInvalidPersistentStateIntoRecords:(id)arg1;
- (void)_invalidateRestorableStateOfContents;
- (BOOL)_contentsHaveInvalidRestorableState;
- (void)_setContentsHaveInvalidRestorableState:(BOOL)arg1;
- (id)initWithWindowID:(unsigned int)arg1;
- (BOOL)_shouldRecordPersistentState;
- (unsigned int)_persistentUIWindowID;

@end

