//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableDictionary, NSURL;

@interface NSPersistentUIWindowSnapshotter : NSObject
{
    NSURL *persistentStateDirectoryURL;
    NSMutableDictionary *windowsPendingSnapshotting;
    NSMutableDictionary *windowIDsToSnapshotInfo;
    BOOL hasDisabledSuddenTermination;
    struct dispatch_queue_s *IOQueue;
    BOOL volumeIsLocal;
    NSData *_cryptoKey;
    NSData *_cryptoUUID;
    unsigned int _cryptoKeyGeneration;
}

@property(copy) NSData *cryptoKey; // @synthesize cryptoKey=_cryptoKey;
@property(copy) NSData *cryptoUUID; // @synthesize cryptoUUID=_cryptoUUID;
- (void)deleteSnapshotForWindowID:(unsigned int)arg1;
- (BOOL)writeWindowSnapshot:(const void *)arg1 length:(unsigned long long)arg2 width:(unsigned long long)arg3 height:(unsigned long long)arg4 bytesPerRow:(unsigned long long)arg5 toFile:(id)arg6 inDirectory:(id)arg7 encryptingWithKey:(id)arg8 uuid:(id)arg9 checksum:(unsigned int *)arg10 isUserWaitingImpatientlyForThisThingToFinish:(BOOL)arg11;
- (void)captureAndWriteSnapshotForWindowNumber:(long long)arg1 forWindowID:(unsigned int)arg2 waitUntilDone:(BOOL)arg3;
- (void)deleteSnapshotForWindowID:(unsigned int)arg1 waitUntilDone:(BOOL)arg2;
- (void)enqueueWindowForSnapshotting:(unsigned int)arg1 forWindowNumber:(long long)arg2 waitUntilDone:(BOOL)arg3;
- (void)finishPendingSnapshots;
- (void)asynchronouslySnapshotPendingWindows;
- (void)synchronouslySnapshotPendingWindows;
- (BOOL)snapshotOnePendingWindowWaitUntilDone:(BOOL)arg1;
- (BOOL)dequeueOneWindowToSnapshot:(unsigned int *)arg1 windowNumber:(long long *)arg2;
- (void)accessWindowBits:(long long)arg1 handler:(CDUnknownBlockType)arg2;
- (BOOL)windowHasBeenSnapshotted:(unsigned int)arg1;
- (void)discardAllSnapshotData;
- (void)updateSuddenTermination;
- (id)persistentStateDirectoryURL;
- (BOOL)setCryptoKey:(id)arg1 uuid:(id)arg2;
- (void)finalize;
- (void)dealloc;
- (id)initWithPersistentStateDirectoryURL:(id)arg1 IOQueue:(struct dispatch_queue_s *)arg2;

@end

