//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSRuleEditorViewSlice.h>

@class NSButton, NSMutableArray;

@interface NSRuleEditorViewSliceRow : NSRuleEditorViewSlice
{
    NSMutableArray *_ruleOptionViews;
    NSMutableArray *_ruleOptionFrames;
    NSMutableArray *_correspondingRuleItems;
    NSMutableArray *_ruleOptionInitialViewFrames;
    NSButton *_addButton;
    NSButton *_subtractButton;
    long long _rowType;
    long long _plusButtonRowType;
    struct {
        unsigned int editable:1;
        unsigned int reserved:31;
    } _sliceRowFlags;
    id _sliceRowReserved;
}

+ (void)initialize;
- (void)viewDidMoveToWindow;
- (id)_subtractButton;
- (id)_addButton;
- (BOOL)isEditable;
- (void)setEditable:(BOOL)arg1;
- (BOOL)_dropsIndentWhenImmediatelyBelow;
- (void)_setRowTypeToAddFromPlusButton:(long long)arg1;
- (BOOL)_plusMinusButtonsAcceptFirstMouse;
- (void)_configurePlusButtonByRowType:(long long)arg1;
- (BOOL)containsDisplayValue:(id)arg1;
- (void)_setRowType:(unsigned long long)arg1;
- (unsigned long long)_rowType;
- (void)_setHideNonPartDrawing:(BOOL)arg1;
- (void)_updateButtonVisibilities;
- (BOOL)_nestingModeShouldHideSubtractButton;
- (BOOL)_nestingModeShouldHideAddButton;
- (void)_deleteOption:(id)arg1;
- (void)_addOption:(id)arg1;
- (void)_reconfigureSubviews;
- (id)_sortOptionDictionariesByLayoutOrder:(id)arg1;
- (void)_updateEnabledStateForSubviews;
- (void)_emptyRulePartSubviews;
- (void)_ruleOptionPopupChangedAction:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)_relayoutSubviewsWidthChanged:(BOOL)arg1;
- (double)_minWidthForPass:(long long)arg1 forView:(id)arg2 withProposedMinWidth:(double)arg3;
- (void)_tightenResizables:(id)arg1 intoGivenWidth:(double)arg2;
- (double)_alignmentGridWidth;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 ruleEditorView:(id)arg2;
- (void)_initShared;
- (BOOL)_isRulePopup:(id)arg1;
- (BOOL)_isRuleStaticTextField:(id)arg1;
- (id)_createMenuSeparatorItem;
- (id)_createMenuItemWithTitle:(id)arg1;
- (id)_createPopUpButtonWithItems:(id)arg1 selectedItemIndex:(long long)arg2;
- (id)_createStaticTextFieldWithStringValue:(id)arg1;
- (id)_createDeleteRowButton;
- (id)_createAddRowButton;
- (double)_rowButtonsInterviewHorizontalPadding;
- (double)_rowButtonsLeftHorizontalPadding;
- (double)_rowButtonsRightHorizontalPadding;
- (double)_indentationHorizontalPadding;
- (double)_leftmostViewFixedHorizontalPadding;
- (double)_minimumVerticalPopupPadding;
- (double)_interviewHorizontalPadding;

@end

