//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface NSScriptSuiteDescription : NSObject
{
    CDStruct_7ffc63f5 _properties;
    NSString *_plistSuiteName;
    BOOL _usesUnnamedArguments;
    char _padding[3];
    NSArray *_unreconciledClassSynonymDescriptions;
    NSArray *_unreconciledClassExtensionDescriptions;
    NSDictionary *_cachedClassDescriptionsByName;
    NSDictionary *_cachedCommandDescriptionsByName;
}

+ (id)currentSuiteTerminology;
+ (unsigned int)currentSuiteAppleEventCode;
+ (id)suiteDescriptionFromPropertyListDeclaration:(id)arg1 bundle:(id)arg2;
+ (id)_typeDescriptionsFromEnumerationImplDeclarations:(id)arg1 presoDeclarations:(id)arg2 valueTypeDeclarations:(id)arg3;
+ (id)_commandDescriptionsFromPropertyListDeclarations:(id)arg1 suiteName:(id)arg2;
+ (id)_classSynonymDescriptionsFromImplDeclarations:(id)arg1 presoDeclarations:(id)arg2;
+ (id)_classDescriptionsFromPropertyListDeclarations:(id)arg1 suiteName:(id)arg2;
+ (id)sortedClassDescriptions:(id)arg1;
- (void)removeCommandDescriptions:(id)arg1;
- (void)setCommandDescription:(id)arg1;
- (void)removeClassDescriptions:(id)arg1;
- (void)setClassDescription:(id)arg1;
- (id)commandDescriptionsByName;
- (id)classDescriptionsByName;
- (BOOL)usesUnnamedArguments;
- (id)firstPresentableName;
- (id)presentableNames;
- (id)presentableDescription;
- (BOOL)isHidden;
- (id)typeDescriptions;
- (id)commandDescriptions;
- (id)classDescriptions;
- (unsigned int)appleEventCode;
- (id)name;
- (id)bundle;
- (void)reconcileSubdescriptionsToSuiteRegistry:(id)arg1;
- (void)reconcileSelfToSuiteRegistry:(id)arg1;
- (void)dealloc;
- (id)initWithProperties:(const CDStruct_7ffc63f5 *)arg1 suiteName:(id)arg2 usesUnnamedArguments:(BOOL)arg3 classSynonymDescriptions:(id)arg4;
- (id)initWithProperties:(const CDStruct_7ffc63f5 *)arg1 classExtensionDescriptions:(id)arg2;
- (unsigned short)appendSuiteDeclarationsToAETEData:(id)arg1;
- (id)description;
- (id)_descriptionWithTabCount:(unsigned long long)arg1;

@end

