//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

@class NSData;

@interface NSSecureTextFieldCell : NSTextFieldCell
{
    BOOL _echosBullets;
    BOOL _csMode;
}

+ (id)_sharedSecureFieldEditor;
+ (void)initialize;
- (id)initWithCoder:(id)arg1;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawLayer:(id)arg1 inGraphicsContext:(id)arg2;
- (BOOL)wantsUpdateLayerInView:(id)arg1;
- (id)_bulletStringForString:(id)arg1;
- (BOOL)echosBullets;
- (void)setEchosBullets:(BOOL)arg1;
- (id)initTextCell:(id)arg1;
- (unsigned short)_bulletCharacter;
- (void)_setBulletCharacter:(unsigned short)arg1;
- (void)selectWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 start:(long long)arg5 length:(long long)arg6;
- (void)editWithFrame:(struct CGRect)arg1 inView:(id)arg2 editor:(id)arg3 delegate:(id)arg4 event:(id)arg5;
- (id)setUpFieldEditorAttributes:(id)arg1;
- (id)fieldEditorForView:(id)arg1;
- (struct _NSRange)textView:(id)arg1 willChangeSelectionFromCharacterRange:(struct _NSRange)arg2 toCharacterRange:(struct _NSRange)arg3;
- (BOOL)validatePasswordSessionValue:(id)arg1;
@property(readonly) NSData *passwordSessionValue; // @dynamic passwordSessionValue;
@property(getter=isKernelSecureMode) BOOL kernelSecureMode; // @dynamic kernelSecureMode;
- (void)finalize;
- (void)dealloc;
- (const void *)_securePromptSession;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (id)accessibilityChildrenAttribute;
- (BOOL)accessibilityIsValueDescriptionAttributeSettable;
- (id)accessibilityValueDescriptionAttribute;
- (id)accessibilityValueAttribute;
- (BOOL)accessibilityIsSubroleAttributeSettable;
- (id)accessibilitySubroleAttribute;
- (id)accessibilityParameterizedAttributeNames;
- (id)accessibilityAttributeNames;

@end

