//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSOverlayScrollerImp.h>

__attribute__((visibility("hidden")))
@interface NSSmallOverlayScrollerImp : NSOverlayScrollerImp
{
}

+ (double)scrollerWidth;
- (void)loadImages;
- (double)knobInset;
- (double)trackOverlapEndInset;
- (double)knobMinLength;
- (double)trackSideInset;
- (double)trackEndInset;
- (double)_expandedTrackWidth;
- (double)trackWidth;
- (unsigned long long)controlSize;

@end

