//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSLayoutConstraint;

__attribute__((visibility("hidden")))
@interface NSStackViewSpacer : NSView
{
    BOOL _vertical;
    double _sideLength;
    float _huggingPriority;
    NSLayoutConstraint *_flexibleWidthConstraint;
    NSLayoutConstraint *_flexibleHeightConstraint;
    NSLayoutConstraint *_rigidWidthConstraint;
    NSLayoutConstraint *_rigidHeightConstraint;
}

+ (id)satisfyingSpacerForSpacer:(id)arg1 andSpacer:(id)arg2;
+ (id)newSpacerWithSideLength:(double)arg1 verticality:(BOOL)arg2 huggingPriority:(float)arg3;
@property float huggingPriority; // @synthesize huggingPriority=_huggingPriority;
@property(retain) NSLayoutConstraint *flexibleHeightConstraint; // @synthesize flexibleHeightConstraint=_flexibleHeightConstraint;
@property(retain) NSLayoutConstraint *flexibleWidthConstraint; // @synthesize flexibleWidthConstraint=_flexibleWidthConstraint;
@property(retain) NSLayoutConstraint *rigidHeightConstraint; // @synthesize rigidHeightConstraint=_rigidHeightConstraint;
@property(retain) NSLayoutConstraint *rigidWidthConstraint; // @synthesize rigidWidthConstraint=_rigidWidthConstraint;
- (void)updateConstraints;
@property(getter=isVertical) BOOL vertical;
@property double sideLength;
- (void)setSideLength:(double)arg1 animated:(BOOL)arg2;
- (void)dealloc;
- (BOOL)shouldBeArchived;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithSideLength:(double)arg1 verticality:(BOOL)arg2 huggingPriority:(float)arg3;
- (id)init;

@end

