//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSGraphicsContext, NSTableView;

@interface NSTableOverlappingColumnClipHelper : NSObject
{
    NSGraphicsContext *_graphicsContext;
    NSTableView *_tableView;
    struct CGRect _origClipRect;
    struct CGRect _currClipRect;
    BOOL _isClipping;
}

- (BOOL)clipForDrawingRow:(long long)arg1 column:(long long)arg2;
- (void)clearClipping;
- (void)dealloc;
- (struct CGRect)currentClipRect;
- (id)initWithTableView:(id)arg1 clipRect:(struct CGRect)arg2;

@end

