//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSImage, NSTableView;

@interface NSTableHeaderView : NSView
{
    NSTableView *_tableView;
    long long _resizedColumn;
    long long _draggedColumn;
    long long _pressedColumn;
    NSImage *_headerDragImage;
    double _draggedDistance;
    unsigned int _isColumnResizing:1;
    unsigned int _showHandCursorFired:1;
    unsigned int _toolTipRectsDirty:1;
    unsigned int _alignTitleWithDataCell:1;
    unsigned int _nextColumnAfterDrawnOneIsSelected:1;
    unsigned int _reserved:27;
    BOOL _skipDrawingSeparator;
    id _viewDataX;
}

- (void)_updateColumnViewWidthsAnimated:(BOOL)arg1;
- (void)_endDraggingColumn:(long long)arg1 animated:(BOOL)arg2;
- (void)_didMoveFromColumn:(long long)arg1 toColumn:(long long)arg2 animated:(BOOL)arg3;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)_setAlignTitleWithDataCell:(BOOL)arg1;
- (BOOL)_alignTitleWithDataCell;
- (double)draggedDistance;
- (long long)draggedColumn;
- (long long)resizedColumn;
- (id)tableView;
- (void)setTableView:(id)arg1;
- (void)_windowChangedKeyState;
- (long long)_resizeableColumnAtPoint:(struct CGPoint)arg1;
- (long long)_previousNonHiddenColumnStartingAtColumn:(long long)arg1;
- (void)resetCursorRects;
- (struct CGRect)_cursorRectForColumn:(long long)arg1;
- (BOOL)isOpaque;
- (BOOL)isFlipped;
- (void)mouseDown:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (BOOL)mouseDownCanMoveWindow;
- (void)drawRect:(struct CGRect)arg1;
- (void)_viewBasedRawRect:(struct CGRect)arg1;
- (void)_switchToNonViewBasedIfNeeded;
- (void)_switchToViewBasedIfNeeded;
- (BOOL)_supportsViewsForAnimations;
- (id)view:(id)arg1 stringForToolTip:(long long)arg2 point:(struct CGPoint)arg3 userData:(void *)arg4;
- (void)_addToolTipRects;
- (void)_invalidateOrComputeNewCursorRectsIfNecessary;
- (void)_setToolTipRectsDirty:(BOOL)arg1;
- (void)_windowKeyChanged:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)_old_encodeWithCoder_NSTableHeaderView:(id)arg1;
- (void)dealloc;
- (void)_startObservingKeyWindow:(id)arg1;
- (void)_stopObservingKeyWindow;
- (BOOL)_isColumnReordering;
- (BOOL)_isColumnResizing;
- (void)_resizeColumn:(long long)arg1 withEvent:(id)arg2;
- (void)_dropTableViewOverdrawIfNecessary;
- (void)_reorderColumn:(long long)arg1 withEvent:(id)arg2;
- (void)_setNeedsDisplayForDraggedDelta:(double)arg1;
- (id)_resizeCursorForTableColumn:(id)arg1;
- (id)_lastDraggedOrUpEventFollowing:(id)arg1 canceled:(char *)arg2;
- (id)_lastDraggedEventFollowing:(id)arg1;
- (void)_endDraggingColumn:(long long)arg1;
- (void)_beginDraggingColumn:(long long)arg1;
- (void)_drawHeaderDragImageForColumn:(long long)arg1;
- (struct CGRect)_unobstructedVisibleHeaderRectOfColumn:(long long)arg1;
- (BOOL)_trackAndModifySelectionWithEvent:(id)arg1 onColumn:(long long)arg2 stopOnReorderGesture:(char *)arg3;
- (void)_scheduleDelayedShowOpenHandCursorIfNecessary;
- (void)_unshowOpenHandCursor:(id)arg1;
- (void)_cancelDelayedShowOpenHandCursor;
- (void)_showOpenHandCursor:(id)arg1;
- (struct CGRect)_headerRectForInvalidation:(long long)arg1;
- (void)_doModifySelectionWithEvent:(id)arg1 onColumn:(long long)arg2;
- (void)_drawColumnHeaderWithIndexes:(id)arg1;
- (BOOL)_drawingEndSeparator;
- (id)_rectsForMultiClippedContentDrawing;
- (BOOL)_hasRowHeaderColumn;
- (struct CGRect)_rowHeaderScrollableContentVisibleRect;
- (struct CGRect)_rowHeaderFixedContentRect;
- (void)_drawRect:(struct CGRect)arg1 liveResizeFill:(struct CGRect)arg2:(struct CGRect)arg3:(struct CGRect)arg4:(struct CGRect)arg5 cacheCoveredArea:(struct CGRect)arg6;
- (void)_drawRect:(struct CGRect)arg1 liveResizeCacheCoveredArea:(struct CGRect)arg2;
- (BOOL)_layoutIsSameAsCachedLayoutWithFrame:(struct CGRect)arg1;
- (void)_invalidateLiveResizeCachedImage;
- (BOOL)_shouldAttemptIdleTimeDisposeOfLiveResizeCacheWithFrame:(struct CGRect)arg1;
- (BOOL)_wantsLiveResizeToUseCachedImage;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)_invalidateRightMostLineIfNeeded;
- (BOOL)preservesContentDuringLiveResize;
- (void)_drawOverflowHeaderInRect:(struct CGRect)arg1;
- (struct CGRect)_overflowRectForBounds:(struct CGRect)arg1;
- (void)_drawHeaderOfColumn:(long long)arg1;
- (BOOL)_nextColumnDrawsLeftSeparatorFromColumn:(long long)arg1;
- (BOOL)_nextColumnAfterOneBeingDrawnIsSelected;
- (id)_preparedHeaderCellAtColumn:(long long)arg1;
- (void)drawBackgroundOverhangInRect:(struct CGRect)arg1;
- (void)_drawHeaderFillerInRect:(struct CGRect)arg1 matchLastState:(BOOL)arg2;
- (id)_preparedHeaderFillerCell;
- (void)_tableView:(id)arg1 didRemoveTableColumnAtIndex:(long long)arg2;
- (void)_tableView:(id)arg1 willRemoveTableColumn:(id)arg2;
- (void)_tableView:(id)arg1 didAddTableColumn:(id)arg2;
- (void)_tableView:(id)arg1 willAddTableColumn:(id)arg2;
- (id)_overflowHeaderCellPrototype;
- (void)_setOverflowHeaderCellPrototype:(id)arg1;
- (void)_drawHeaderCell:(id)arg1 withFrame:(struct CGRect)arg2 withStateFromColumn:(long long)arg3;
- (long long)columnAtPoint:(struct CGPoint)arg1;
- (struct CGRect)headerRectOfColumn:(long long)arg1;
- (id)init;
- (id)accessibilitySizeOfChild:(id)arg1;
- (id)accessibilityPositionOfChild:(id)arg1;
- (BOOL)accessibilityIsChildFocusable:(id)arg1;
- (id)accessibilityHelpStringForChild:(id)arg1;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityChildrenAttribute;
- (id)accessibilityParentAttribute;
- (id)accessibilityRoleAttribute;
- (unsigned long long)accessibilityColumnForChild:(id)arg1;
- (id)accessibilityChildForColumn:(id)arg1;

@end

