//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import "NSChangeSpelling.h"
#import "NSIgnoreMisspelledWords.h"

@interface NSText : NSView <NSChangeSpelling, NSIgnoreMisspelledWords>
{
    id _ivars;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)initialize;
- (void)ignoreSpelling:(id)arg1;
- (void)changeSpelling:(id)arg1;
- (void)scrollRangeToVisible:(struct _NSRange)arg1;
- (void)setSelectedRange:(struct _NSRange)arg1;
- (struct _NSRange)selectedRange;
- (BOOL)isRulerVisible;
- (void)toggleRuler:(id)arg1;
- (void)checkSpelling:(id)arg1;
- (void)showGuessPanel:(id)arg1;
- (void)unscript:(id)arg1;
- (void)underline:(id)arg1;
- (void)superscript:(id)arg1;
- (void)subscript:(id)arg1;
- (void)alignCenter:(id)arg1;
- (void)alignRight:(id)arg1;
- (void)alignLeft:(id)arg1;
- (void)changeFont:(id)arg1;
- (void)selectAll:(id)arg1;
- (void)pasteRuler:(id)arg1;
- (void)pasteFont:(id)arg1;
- (void)paste:(id)arg1;
- (void)delete:(id)arg1;
- (void)cut:(id)arg1;
- (void)copyRuler:(id)arg1;
- (void)copyFont:(id)arg1;
- (void)copy:(id)arg1;
- (void)sizeToFit;
- (void)setVerticallyResizable:(BOOL)arg1;
- (BOOL)isVerticallyResizable;
- (void)setHorizontallyResizable:(BOOL)arg1;
- (BOOL)isHorizontallyResizable;
- (void)setMinSize:(struct CGSize)arg1;
- (struct CGSize)minSize;
- (void)setMaxSize:(struct CGSize)arg1;
- (struct CGSize)maxSize;
- (void)setUsesFontPanel:(BOOL)arg1;
- (BOOL)usesFontPanel;
- (void)setFont:(id)arg1 range:(struct _NSRange)arg2;
- (void)setTextColor:(id)arg1 range:(struct _NSRange)arg2;
- (BOOL)isFieldEditor;
- (void)setFieldEditor:(BOOL)arg1;
- (void)setBaseWritingDirection:(long long)arg1;
- (long long)baseWritingDirection;
- (void)setAlignment:(unsigned long long)arg1;
- (unsigned long long)alignment;
- (BOOL)drawsBackground;
- (void)setDrawsBackground:(BOOL)arg1;
- (id)backgroundColor;
- (void)setBackgroundColor:(id)arg1;
- (id)textColor;
- (void)setTextColor:(id)arg1;
- (id)font;
- (void)setFont:(id)arg1;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)setImportsGraphics:(BOOL)arg1;
- (BOOL)importsGraphics;
- (void)setRichText:(BOOL)arg1;
- (BOOL)isRichText;
- (void)setSelectable:(BOOL)arg1;
- (BOOL)isSelectable;
- (void)setEditable:(BOOL)arg1;
- (BOOL)isEditable;
- (BOOL)readRTFDFromFile:(id)arg1;
- (BOOL)writeRTFDToFile:(id)arg1 atomically:(BOOL)arg2;
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withRTFD:(id)arg2;
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withRTF:(id)arg2;
- (id)RTFDFromRange:(struct _NSRange)arg1;
- (id)RTFFromRange:(struct _NSRange)arg1;
- (void)replaceCharactersInRange:(struct _NSRange)arg1 withString:(id)arg2;
- (void)setString:(id)arg1;
- (id)string;
- (id)accessibilityTextLinkAtIndex:(unsigned long long)arg1;
- (id)accessibilityTextLinks;
- (id)accessibilityAttachmentAtIndex:(unsigned long long)arg1;
- (unsigned long long)accessibilityIndexForAttachment:(id)arg1;
- (id)accessibilityAttachments;
- (struct _NSRange)accessibilitySharedCharacterRange;
- (id)accessibilitySharedTextViews;
- (struct _NSRange)accessibilityStyleRangeForCharacterIndex:(unsigned long long)arg1;
- (id)accessibilityAXAttributedStringForCharacterRange:(struct _NSRange)arg1 parent:(id)arg2;
- (id)accessibilityRTFForCharacterRange:(struct _NSRange)arg1;
- (struct CGRect)accessibilityBoundsForCharacterRange:(struct _NSRange)arg1;
- (struct _NSRange)accessibilityCharacterRangeForPosition:(struct CGPoint)arg1;
- (struct _NSRange)accessibilityCharacterRangeForLineNumber:(unsigned long long)arg1;
- (unsigned long long)accessibilityLineNumberForCharacterIndex:(unsigned long long)arg1;
- (unsigned long long)accessibilityInsertionPointLineNumber;
- (void)accessibilitySetVisibleCharacterRange:(struct _NSRange)arg1;
- (BOOL)accessibilityIsVisibleCharacterRangeSettable;
- (struct _NSRange)accessibilityVisibleCharacterRange;
- (id)accessibilityTextView;
- (void)accessibilitySetSelectedRange:(struct _NSRange)arg1;
- (BOOL)accessibilityIsSelectedRangeSettable;
- (struct _NSRange)accessibilitySelectedRange;
- (void)accessibilitySetSelectedText:(id)arg1;
- (BOOL)accessibilityIsSelectedTextSettable;
- (id)accessibilitySelectedText;
- (id)accessibilityValueAttribute;
- (void)accessibilityPostNotification:(id)arg1;
- (void)accessibilityPostNotification:(id)arg1 withNotificationElement:(id)arg2;

@end

