//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSSearchField.h>

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface NSTextFinderBarSearchField : NSSearchField
{
}

- (void)mouseDown:(id)arg1;
- (BOOL)needsPanelToBecomeKey;
- (BOOL)_mouseDownEventIsInSearchButton:(id)arg1;
@property(copy) NSArray *recentAttributedSearchStrings;
@property(copy) NSString *statusString;

@end

