//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString;

@interface NSTextPlaceholder : NSObject
{
    id _owner;
    id _text;
    BOOL _committed;
    id _internal;
}

@property(readonly) BOOL committed; // @synthesize committed=_committed;
@property(readonly) NSAttributedString *attributedStringValue; // @synthesize attributedStringValue=_text;
- (void)_postCommitNotification;
- (void)setText:(id)arg1 doCommit:(BOOL)arg2;
- (void)commit;
@property id owner; // @dynamic owner;
- (id)identifier;
- (void)dealloc;
- (id)initWithIdentifier:(id)arg1 text:(id)arg2 doCommit:(BOOL)arg3;

@end

