//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface NSUndoManager : NSObject
{
    id _undoStack;
    id _redoStack;
    NSArray *_runLoopModes;
    unsigned long long _NSUndoManagerPrivate1;
    id _target;
    id _proxy;
    void *_NSUndoManagerPrivate2;
    void *_NSUndoManagerPrivate3;
}

+ (void)_endTopLevelGroupings;
+ (void)_setEndsTopLevelGroupingsAfterRunLoopIterations:(BOOL)arg1;
- (id)redoMenuTitleForUndoActionName:(id)arg1;
- (id)undoMenuTitleForUndoActionName:(id)arg1;
- (id)redoMenuItemTitle;
- (id)undoMenuItemTitle;
- (BOOL)redoActionIsDiscardable;
- (BOOL)undoActionIsDiscardable;
- (void)setActionIsDiscardable:(BOOL)arg1;
- (void)setActionName:(id)arg1;
- (void)_setGroupIdentifier:(id)arg1;
- (id)redoActionName;
- (id)undoActionName;
- (void)registerUndoWithTarget:(id)arg1 selector:(SEL)arg2 arguments:(id *)arg3 argumentCount:(unsigned long long)arg4;
- (void)registerUndoWithTarget:(id)arg1 selector:(SEL)arg2 object:(id)arg3;
- (void)_forwardTargetInvocation:(id)arg1;
- (void)_registerUndoObject:(id)arg1;
- (id)_methodSignatureForTargetSelector:(SEL)arg1;
- (id)prepareWithInvocationTarget:(id)arg1;
- (void)removeAllActionsWithTarget:(id)arg1;
- (void)removeAllActions;
- (BOOL)isRedoing;
- (BOOL)isUndoing;
- (BOOL)canRedo;
- (BOOL)canUndo;
- (void)redo;
- (void)undoNestedGroup;
- (void)undo;
- (id)runLoopModes;
- (void)setRunLoopModes:(id)arg1;
- (unsigned long long)levelsOfUndo;
- (void)setLevelsOfUndo:(unsigned long long)arg1;
- (void)setGroupsByEvent:(BOOL)arg1;
- (BOOL)groupsByEvent;
- (BOOL)isUndoRegistrationEnabled;
- (void)enableUndoRegistration;
- (void)disableUndoRegistration;
- (void)endUndoGrouping;
- (BOOL)_endUndoGroupRemovingIfEmpty:(BOOL)arg1;
- (long long)groupingLevel;
- (void)beginUndoGrouping;
- (void)_postCheckpointNotification;
- (void)_prepareEventGrouping;
- (void)_cancelAutomaticTopLevelGroupEnding;
- (void)_scheduleAutomaticTopLevelGroupEnding;
- (void)_delayAutomaticTermination:(double)arg1;
- (void)finalize;
- (void)dealloc;
- (id)init;
- (void)_rollbackUndoGrouping;
- (void)_commitUndoGrouping;
- (void)_processEndOfEventNotification:(id)arg1;
- (BOOL)_shouldCoalesceTypingForText:(id)arg1:(id)arg2;
- (id)_undoStack;

@end

