//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface NSURLProtocolCFNetwork : NSObject
{
    Class clazz;
}

+ (Class)_protocolClassForRequest:(id)arg1 allowCF:(BOOL)arg2;
- (BOOL)_requestIsCacheEquivalent:(id)arg1 toRequest:(id)arg2 allowCF:(BOOL)arg3;
- (id)_canonicalRequestForRequest:(id)arg1 allowCF:(BOOL)arg2;
- (Class)_protocolClassForRequest:(id)arg1 allowCF:(BOOL)arg2;
- (id)initWithClass:(Class)arg1;

@end

