//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSView.h>

@interface NSView (WebExtras)
- (struct CGRect)_web_convertRect:(struct CGRect)arg1 toView:(id)arg2;
- (BOOL)_web_firstResponderIsSelfOrDescendantView;
- (void)_web_DragImageForElement:(id)arg1 rect:(struct CGRect)arg2 event:(id)arg3 pasteboard:(id)arg4 source:(id)arg5 offset:(struct CGPoint *)arg6;
- (unsigned long long)_web_dragOperationForDraggingInfo:(id)arg1;
- (BOOL)_web_dragShouldBeginFromMouseDown:(id)arg1 withExpiration:(id)arg2;
- (BOOL)_web_dragShouldBeginFromMouseDown:(id)arg1 withExpiration:(id)arg2 xHysteresis:(float)arg3 yHysteresis:(float)arg4;
- (id)_webView;
- (id)_web_parentWebFrameView;
- (id)_web_superviewOfClass:(Class)arg1;
@end

