//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSResponder.h>

#import "NSCoding.h"

@class NSArray, NSBundle, NSPointerArray, NSString, NSView;

@interface NSViewController : NSResponder <NSCoding>
{
    NSString *_nibName;
    NSBundle *_nibBundle;
    id _representedObject;
    NSString *_title;
    NSView *view;
    NSArray *_topLevelObjects;
    NSPointerArray *_editors;
    id _autounbinder;
    NSString *_designNibBundleIdentifier;
    id _reserved[2];
}

- (id)_autounbinder;
- (void)discardEditing;
- (BOOL)commitEditingAndReturnError:(id *)arg1;
- (BOOL)commitEditing;
- (void)_editor:(id)arg1 didCommit:(BOOL)arg2 withOriginalDelegateInvocation:(id)arg3;
- (void)commitEditingWithDelegate:(id)arg1 didCommitSelector:(SEL)arg2 contextInfo:(void *)arg3;
- (id)_topEditor;
- (void)objectDidEndEditing:(id)arg1;
- (void)objectDidBeginEditing:(id)arg1;
- (void)setView:(id)arg1;
- (id)nibBundle;
- (id)nibName;
- (void)loadView;
- (void)_setTopLevelObjects:(id)arg1;
- (id)view;
- (id)title;
- (void)setTitle:(id)arg1;
- (id)representedObject;
- (void)setRepresentedObject:(id)arg1;
- (void)dealloc;
- (oneway void)release;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)init;
- (void)_setNibName:(id)arg1;
- (id)_nibBundleIdentifier;
- (void)_setNibBundleIdentifier:(id)arg1;
- (id)_representedObject;
- (id)_view;
- (id)_nibWithName:(id)arg1 bundle:(id)arg2;

@end

