//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSManagedObjectContext, NSXPCStoreConnectionInfo;

__attribute__((visibility("hidden")))
@interface NSXPCStoreServerConnectionContext : NSObject
{
    NSManagedObjectContext *_context;
    NSXPCStoreConnectionInfo *_info;
}

- (void)setUserInfo:(id)arg1;
- (id)userInfo;
- (void)setManagedObjectContext:(id)arg1;
- (id)managedObjectContext;
- (CDStruct_4c969caf)auditToken;
- (id)persistentStoreCoordinator;
- (id)entitlements;
- (void)dealloc;
- (id)description;
- (id)initWithConnectionInfo:(id)arg1;

@end

