//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <PerformanceAnalysis/PARangeContainer.h>

#import "NSCoding.h"

@class NSArray, NSString, PAImage;

@interface PAImageSegment : PARangeContainer <NSCoding>
{
    NSString *name;
    PAImage *parentImage;
    NSArray *sections;
}

+ (id)sharedCacheSegment;
@property(retain) NSArray *sections; // @synthesize sections;
@property PAImage *parentImage; // @synthesize parentImage;
@property(retain) NSString *name; // @synthesize name;
- (long long)compare:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)sectionsStringWithPrefix:(id)arg1;
- (id)summaryString;
- (void)dealloc;
- (id)initWithImage:(id)arg1 SegmentCSRegion:(struct _CSTypeRef)arg2 Sections:(struct _CSTypeRef)arg3;

@end

