//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSImage, PDFCoachMark;

@interface PDFCoachMarkView : NSView
{
    PDFCoachMark *_coach;
    NSImage *_contentImage;
    struct CGPoint _imageOffset;
}

- (double)bottomBorder;
- (double)rightBorder;
- (double)topBorder;
- (double)leftBorder;
- (void)drawRect:(struct CGRect)arg1;
- (void)_drawGradientInRect:(struct CGRect)arg1;
- (struct CGRect)contentRect;
- (id)roundedRect:(struct CGRect)arg1 withRadius:(float)arg2;
- (id)initWithCoach:(id)arg1 contentRect:(struct CGRect)arg2 contentImage:(id)arg3;
- (void)dealloc;

@end

