//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface PFUbiquityLogging : NSObject
{
    int _desiredLogLevel;
}

+ (BOOL)canLogMessageAtLevel:(int)arg1;
+ (void)setLoggingLevel:(int)arg1;
+ (void)initialize;
@property(nonatomic) int desiredLogLevel; // @synthesize desiredLogLevel=_desiredLogLevel;
- (void)userDefaultsChanged:(id)arg1;
- (void)checkUserDefaults;
- (void)dealloc;
- (id)init;

@end

