//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface VMUFatArch : NSObject
{
    unsigned int _fileOffset;
    unsigned int _size;
    unsigned int _alignment;
    id <VMUMemory> _memory;
}

+ (id)fatArchWithMemory:(id)arg1 fileOffset:(unsigned int)arg2 size:(unsigned int)arg3 alignment:(unsigned int)arg4;
+ (id)fatArchWithMemory:(id)arg1 memoryView:(id)arg2;
- (void)dealloc;
- (id)memory;
- (unsigned int)alignment;
- (unsigned int)size;
- (unsigned int)fileOffset;
- (id)architecture;
- (id)initWithMemory:(id)arg1 memoryView:(id)arg2;
- (id)initWithMemory:(id)arg1 fileOffset:(unsigned int)arg2 size:(unsigned int)arg3 alignment:(unsigned int)arg4;

@end

