//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WebFontCache : NSObject
{
}

+ (id)fontWithFamily:(id)arg1 traits:(unsigned long long)arg2 size:(float)arg3;
+ (id)fontWithFamily:(id)arg1 traits:(unsigned long long)arg2 weight:(int)arg3 size:(float)arg4;
+ (id)internalFontWithFamily:(id)arg1 traits:(unsigned long long)arg2 weight:(int)arg3 size:(float)arg4;
+ (void)getTraits:(Vector_823c03ea *)arg1 inFamily:(id)arg2;

@end

