//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSButton, NSControl, NSTextField, NSTimer, NSTrackingArea;

__attribute__((visibility("hidden")))
@interface WebVideoFullscreenHUDWindowController : NSWindowController
{
    id <WebVideoFullscreenHUDWindowControllerDelegate> _delegate;
    NSTimer *_timelineUpdateTimer;
    NSTrackingArea *_area;
    BOOL _mouseIsInHUD;
    BOOL _isEndingFullscreen;
    BOOL _isScrubbing;
    NSControl *_timeline;
    NSTextField *_remainingTimeText;
    NSTextField *_elapsedTimeText;
    NSControl *_volumeSlider;
    NSButton *_playButton;
}

- (void)windowDidClose:(id)arg1;
- (void)windowDidExpose:(id)arg1;
- (void)exitFullscreen:(id)arg1;
- (void)fastForward:(id)arg1;
- (void)rewind:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (id)elapsedTimeText;
- (id)remainingTimeText;
- (void)setPlaying:(BOOL)arg1;
- (BOOL)playing;
- (void)togglePlaying:(id)arg1;
- (void)updateRate;
- (void)updatePlayButton;
- (void)setVolume:(float)arg1;
- (float)volume;
- (void)incrementVolume;
- (void)decrementVolume;
- (void)setVolumeToMaximum:(id)arg1;
- (void)setVolumeToZero:(id)arg1;
- (void)volumeChanged:(id)arg1;
- (float)maxVolume;
- (double)duration;
- (void)setCurrentTime:(float)arg1;
- (float)currentTime;
- (void)timelinePositionChanged:(id)arg1;
- (void)endScrubbing;
- (void)updateTime;
- (void)updateVolume;
- (void)windowDidLoad;
- (void)closeWindow;
- (void)fadeWindowOut;
- (void)fadeWindowIn;
- (void)unscheduleTimeUpdate;
- (void)scheduleTimeUpdate;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)keyDown:(id)arg1;
- (void)setArea:(id)arg1;
- (void)dealloc;
- (id)init;

@end

