//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSEvent;

__attribute__((visibility("hidden")))
@interface WKViewData : NSObject
{
    struct OwnPtr<WebKit::PageClientImpl> _pageClient;
    struct RefPtr<WebKit::WebPageProxy> _page;
    struct RetainPtr<WKBrowsingContextController> _browsingContextController;
    long long _lastToolTipTag;
    id _trackingRectOwner;
    void *_trackingRectUserData;
    struct RetainPtr<NSView> _layerHostingView;
    struct RetainPtr<id> _remoteAccessibilityChild;
    struct HashMap<WTF::String, WTF::Vector<WTF::RetainPtr<id<NSValidatedUserInterfaceItem>>, 0, WTF::CrashOnOverflow>, WTF::StringHash, WTF::HashTraits<WTF::String>, WTF::HashTraits<WTF::Vector<WTF::RetainPtr<id<NSValidatedUserInterfaceItem>>, 0, WTF::CrashOnOverflow>>> _validationMap;
    struct OwnPtr<WebKit::PDFViewController> _pdfViewController;
    struct OwnPtr<WebKit::FindIndicatorWindow> _findIndicatorWindow;
    struct RetainPtr<NSEvent> _keyDownEventBeingResent;
    struct WKViewInterpretKeyEventsParameters *_interpretKeyEventsParameters;
    struct CGSize _resizeScrollOffset;
    unsigned long long _pluginComplexTextInputIdentifier;
    int _pluginComplexTextInputState;
    _Bool _inBecomeFirstResponder;
    _Bool _inResignFirstResponder;
    NSEvent *_mouseDownEvent;
    BOOL _ignoringMouseDraggedEvents;
    id _flagsChangedEventMonitor;
    id _endGestureMonitor;
    struct RetainPtr<WKFullScreenWindowController> _fullScreenWindowController;
    BOOL _hasSpellCheckerDocumentTag;
    long long _spellCheckerDocumentTag;
    BOOL _inSecureInputState;
    struct CGRect _windowBottomCornerIntersectionRect;
    unsigned int _frameSizeUpdatesDisabledCount;
    BOOL _shouldDeferViewInWindowChanges;
    BOOL _viewInWindowChangeWasDeferred;
    BOOL _needsViewFrameInWindowCoordinates;
    BOOL _didScheduleWindowAndViewFrameUpdate;
    BOOL _windowHasValidBackingStore;
    struct RetainPtr<NSColorSpace> _colorSpace;
    struct RefPtr<WebCore::Image> _promisedImage;
    struct String _promisedFilename;
    struct String _promisedURL;
    struct CGPoint _frameOrigin;
    int _contentAnchor;
    struct CGSize _intrinsicContentSize;
    BOOL _clipsToVisibleRect;
    struct CGRect _contentPreparationRect;
    BOOL _useContentPreparationRectForVisibleRect;
    BOOL _isWindowOccluded;
    BOOL _windowOcclusionDetectionEnabled;
}

- (id).cxx_construct;
- (void).cxx_destruct;

@end

