//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScrollView.h"

@interface DTFocusableScrollView : NSScrollView
{
    BOOL drawsFocusRing;
}

- (void)setFrameOrigin:(struct CGPoint)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)viewWillDraw;
- (void)setDrawsFocusRing:(BOOL)arg1;
- (BOOL)drawsFocusRing;
- (void)setNilValueForKey:(id)arg1;

@end

