//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <IBFoundation/IBICAbstractCatalogItem.h>

@class IBICMultipartImageRepSlot, NSData, NSString, NSValue;

@interface IBICMultipartImageRep : IBICAbstractCatalogItem
{
    NSValue *_imageDataPixelSize;
    BOOL _imageDataPixelSizeIsValid;
    BOOL _unassigned;
    IBICMultipartImageRepSlot *_slot;
    NSData *_imageData;
}

+ (id)keysThatImpactDisplayOrder;
+ (id)validSourceImageExtensions;
+ (id)imageRepWithRepIdentifier:(id)arg1;
+ (id)imageRepWithSlot:(id)arg1 fileName:(id)arg2 andUnassigned:(BOOL)arg3;
+ (Class)slotClass;
+ (Class)multiplartImageClass;
+ (Class)repIdentifierClass;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(copy, nonatomic) NSData *imageData; // @synthesize imageData=_imageData;
@property(copy, nonatomic) IBICMultipartImageRepSlot *slot; // @synthesize slot=_slot;
@property(nonatomic, getter=isUnassigned) BOOL unassigned; // @synthesize unassigned=_unassigned;
- (void).cxx_destruct;
- (id)suggestedFileName;
@property(readonly) NSValue *imageDataPixelSize;
@property(readonly) NSValue *requiredPointSize;
@property(readonly) NSValue *requiredPixelSize;
- (void)populateIssues:(id)arg1 context:(id)arg2;
- (BOOL)updateModificationDatesWithMutationResult:(id)arg1;
- (void)setImageDataFromPath:(id)arg1;
- (BOOL)fileStructureSnapshotChildWouldMapToModelChild:(id)arg1;
- (long long)compareDisplayOrder:(id)arg1;
- (void)replaceChildrenFromFileSystemSnapshot:(id)arg1 results:(id)arg2;
- (id)fileWrapperRepresentationWithOptions:(unsigned long long)arg1;
- (id)parent;
- (void)enumerateDescriptionAttributeComponents:(CDUnknownBlockType)arg1;
- (BOOL)isBrokenFileReference;
- (id)identifier;
- (id)structuredIdentifier;
- (BOOL)canBeEmbeddedInFolder;
- (BOOL)canHaveChildren;
- (id)descriptionShortClassName;
- (BOOL)isMinimallyFitForCompiling;
@property(readonly) NSString *shortDisplayName;
- (id)displayName;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithSlot:(id)arg1;
- (id)init;

@end

