//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@interface NSDictionary (IBDictionaryAdditions)
+ (id)ib_dictionaryWithIntrinsicallyKeyedValues:(id)arg1 intrinsicKeyAccessor:(CDUnknownBlockType)arg2;
+ (id)ib_strictDictionaryWithKeysAndObjects:(id)arg1;
+ (id)ib_dictionaryOfMultiValuedObjects:(id)arg1 keyedByKeyPath:(id)arg2;
+ (id)ib_dictionaryOfObjects:(id)arg1 keyedByKeyPath:(id)arg2;
+ (Class)ib_mutableClass;
- (id)ib_objectForClassKey:(Class)arg1;
- (long long)ib_integerForKey:(id)arg1;
- (double)ib_doubleForKey:(id)arg1 defaultValue:(double)arg2;
- (long long)ib_integerForKey:(id)arg1 defaultValue:(long long)arg2;
- (id)ib_objectArrayForKeyArray:(id)arg1;
- (id)ib_allElementsOfValueCollections;
- (id)ib_sortedKeysByComparingValuesWithSelector:(SEL)arg1;
- (id)ib_invertedMultiValueDictionaryUsingMutableDictionaryClass:(Class)arg1;
- (id)ib_invertedMultiValueDictionary;
- (id)ib_invertedDictionaryUsingMutableDictionaryClass:(Class)arg1;
- (id)ib_invertedDictionary;
- (id)ib_dictionaryBySettingObject:(id)arg1 forKey:(id)arg2;
- (id)ib_objectForKey:(id)arg1 inDictionaryForKey:(id)arg2;
- (id)ib_dictionaryByMappingBlock:(CDUnknownBlockType)arg1;
- (Class)ib_mutableClass;
@end

