//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperationQueue.h"

@interface NSOperationQueue (IBOperationQueueAdditions)
- (void)ib_addOperationWithBlock:(CDUnknownBlockType)arg1 waitUntilFinished:(BOOL)arg2;
@end

