//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Named Structures

struct _XDSCClassCompactVariables {
    unsigned int hasInitializedProperties:1;
    unsigned int hasInitializedOperations:1;
    unsigned int RESERVED1:2;
    unsigned int isCategory:1;
    unsigned int isInProject:1;
    unsigned int hasDocumentation:1;
    unsigned int showOption:3;
    unsigned int SHOW_OPTION_RESERVED:1;
    unsigned int filterState:3;
    unsigned int FILTER_STATE_RESERVED:1;
    unsigned int language:7;
    unsigned int showInBrowser:1;
    unsigned int LEFTOVER_RESERVED:9;
};

struct _XDSCInterfaceCompactVariables {
    unsigned int hasInitializedProperties:1;
    unsigned int hasInitializedOperations:1;
    unsigned int RESERVED1:2;
    unsigned int IS_CATEGORY_RESERVED:1;
    unsigned int isInProject:1;
    unsigned int hasDocumentation:1;
    unsigned int showOption:3;
    unsigned int SHOW_OPTION_RESERVED:1;
    unsigned int filterState:3;
    unsigned int FILTER_STATE_RESERVED:1;
    unsigned int language:7;
    unsigned int showInBrowser:1;
    unsigned int LEFTOVER_RESERVED:9;
};

