//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XDUMLHelper : NSObject
{
}

+ (id)uniqueStringValue:(id)arg1 inObjectArray:(id)arg2 objectKey:(id)arg3;
+ (id)uniqueStringValue:(id)arg1 inStringArray:(id)arg2;
+ (id)findElementNamed:(id)arg1 inArray:(id)arg2;
+ (id)findElementNamed:(id)arg1 inArray:(id)arg2 forSelector:(SEL)arg3;

@end

