//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class DSADocSetGroup, NSArray;

@protocol DSMSubscriptionUpdateProtocol
- (void)docSetGroup:(DSADocSetGroup *)arg1 updateItemsModified:(NSArray *)arg2;
- (void)docSetGroup:(DSADocSetGroup *)arg1 updateItemsRemoved:(NSArray *)arg2;
- (void)docSetGroup:(DSADocSetGroup *)arg1 updateItemsAdded:(NSArray *)arg2;
@end

