//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsInterface/PBXBuildPhaseModule.h>

@class NSMenu, PBXFileBuildPhaseModuleOutlineView;

@interface PBXFileBuildPhaseModule : PBXBuildPhaseModule
{
    PBXFileBuildPhaseModuleOutlineView *_buildFilesOutline;
    NSMenu *_viewContextualMenuTemplate;
    NSMenu *_viewContextualMenu;
    double _viewHeightSansOutline;
    struct {
        unsigned int observingTarget:1;
        unsigned int RESERVED:31;
    } _fbpmFlags;
}

- (void)setSelectedProjectItems:(id)arg1;
- (id)selectedProjectItems;
- (void)targetBuildWillBegin:(id)arg1;
- (id)bookmarksForCurrentSelection;
- (void)revealCurrentFileInGroupTree:(id)arg1;
- (BOOL)validateLocalMenuItem:(id)arg1;
- (void)update;
- (void)_resizeOutlineViewIfNeeded;
- (void)outlineViewShowInspector:(id)arg1;
- (void)outlineViewAttributeChanged:(id)arg1;
- (void)outlineViewBuildStatusChanged:(id)arg1;
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (void)outlineView:(id)arg1 deleteItems:(id)arg2;
- (void)delete:(id)arg1;
- (void)deleteItems:(id)arg1;
- (void)_confirmDeleteSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)setAttributeFromContextMenu:(id)arg1;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)sortSelectedItems:(id)arg1;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (id)label;
- (void)moduleViewWillBeRemoved:(id)arg1;
- (void)moduleViewWasInstalled:(id)arg1;
- (void)viewDidLoad;
- (long long)numberOfAttributeColumns;
- (long long)firstAttributeColumn;
- (void)dealloc;
- (id)initWithBuildPhase:(id)arg1;

@end

