//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSButton, NSMatrix, NSTextField, NSTextView;

@interface PBXGotoPanelController : NSWindowController
{
    NSTextField *textField;
    NSButton *gotoButton;
    NSMatrix *radioButtons;
    NSButton *autoupdateCheckbox;
    NSTextView *autoupdateTextView;
    BOOL autoupdateFlag;
}

+ (struct _NSRange)rangeFromRangeSpecification:(id)arg1;
+ (id)rangeSpecificationFromRange:(struct _NSRange)arg1;
+ (id)sharedGotoPanelController;
- (void)selectRangeText;
- (void)_applicationWillUpdate:(id)arg1;
- (void)textViewSelectionChanged:(id)arg1;
- (void)updateFieldFromTextView:(id)arg1;
- (void)textFieldAction:(id)arg1;
- (void)gotoAction:(id)arg1;
- (void)autoupdateAction:(id)arg1;
- (void)changeRangeTypeAction:(id)arg1;
- (void)windowDidLoad;
- (void)dealloc;
- (id)init;

@end

