//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PBXLSDebuggingSystem : NSObject
{
}

+ (id)localizedStringForContinueToLocation:(id)arg1;
+ (id)localizedStringForDataFetchTimeout;
+ (id)localizedStringForFixAndContinueSheetTitle;
+ (id)localizedStringForOKButtonLabel;
+ (id)localizedStringForFixAndContinueStarted;
+ (id)localizedStringForDebuggerStopped;
+ (id)localizedStringForFixAndContinuePatchedFile:(id)arg1 patchFile:(id)arg2;
+ (id)localizedStringForFixAndContinueError:(id)arg1 WithFile:(id)arg2;
+ (id)localizedStringForMovePC:(id)arg1;
+ (id)localizedStringForMovePCFailed:(id)arg1;
+ (id)localizedStringForLoadingTotalStackFrames:(long long)arg1 percentDone:(long long)arg2;
+ (id)localizedStringForLoadingSymbolsForSharedLibrary:(id)arg1;
+ (id)localizedStringForLoadedSharedLibraries:(long long)arg1;
+ (id)localizedStringForLoadedOneSharedLibrary;
+ (id)localizedStringForFailedLoadingExecutable;
+ (id)localizedStringForDoneLoadingExecutable;
+ (id)localizedStringForLoadingExecutable;
+ (id)localizedStringForStateExitedWithValue:(int)arg1;
+ (id)localizedStringForStateGotUncaughtException:(id)arg1;
+ (id)localizedStringForStateGotCaughtException:(id)arg1;
+ (id)localizedStringForStateGotSignal:(id)arg1;
+ (id)localizedStringForStateStepCompleted;
+ (id)localizedStringForStateAtWatchpoint;
+ (id)localizedStringForStateAtBreakpointNumber;
+ (id)localizedStringForStateAtBreakpoint;
+ (id)localizedStringForStateNotExecuting;
+ (id)localizedStringForStateStopped;
+ (id)localizedStringForStateInterrupted;
+ (id)localizedStringForStateRunning;
+ (id)localizedStringForStateSteppingOut;
+ (id)localizedStringForStateSteppingInto;
+ (id)localizedStringForStateStepInstruction;
+ (id)localizedStringForStateNextInstruction;
+ (id)localizedStringForStateSteppingOver;
+ (id)_myBundle;

@end

