//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsInterface/PBXModule.h>

@class NSArrayController, NSPathControl, NSSearchField, NSTableColumn, NSTableView, NSView, PBXCompletionManager, _XCOQDataSource, _XCOQQuery;

@interface PBXOpenQuicklyModule : PBXModule
{
    NSSearchField *_searchField;
    NSArrayController *_arrayController;
    NSTableView *_tableView;
    NSTableColumn *_matchStringTableColumn;
    NSPathControl *_pathControl;
    NSView *_helpTextBackgroundView;
    _XCOQQuery *_query;
    _XCOQDataSource *_dataSource;
    PBXCompletionManager *_completionManager;
    double _minWidth;
}

+ (BOOL)_skipOpenQuicklyPanelForContext:(id)arg1;
+ (unsigned long long)_skipPanelBehaviour;
+ (id)_pathForMatch:(id)arg1;
+ (id)keyPathsForValuesAffectingIndexingHeaders;
+ (id)sharedOpenQuicklyModule;
@property _XCOQDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain) _XCOQQuery *query; // @synthesize query=_query;
- (void)pathControlAction:(id)arg1;
- (void)tableDoubleClickAction:(id)arg1;
- (void)cancelAction:(id)arg1;
- (void)okAction:(id)arg1;
- (void)_openSelectedMatchesClosingPanelIfSuccessful:(BOOL)arg1;
- (void)searchAction:(id)arg1;
- (void)runOpenThisQuickly:(id)arg1;
- (void)runOpenQuickly:(id)arg1;
- (void)_runOpenQuicklyWhileFeelingLucky:(BOOL)arg1;
- (BOOL)_openMatches:(id)arg1 forInput:(id)arg2;
- (BOOL)_openSingleMatch:(id)arg1 forInput:(id)arg2;
- (void)_keyWindowHack;
@property(readonly) BOOL indexingHeaders;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_projectWillClose:(id)arg1;
- (void)_windowWillClose:(id)arg1;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)controlTextDidEndEditing:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)_setSearchString:(id)arg1;
- (void)_removeHelpTextIfNeeded;
- (id)loadModuleWindow;
- (struct CGSize)viewMinSize;
- (id)moduleWindowFrameAutosaveName;
- (unsigned long long)moduleWindowStyleMask;
- (Class)moduleWindowClass;
- (void)_clearQuery;
- (void)_createQueryIfNeededUsingInputFromCurrentSelection:(BOOL)arg1;
- (id)_projectFolderPath;
- (void)_setInput:(id)arg1;
- (id)_input;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithModuleNibName:(id)arg1;

@end

