//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsInterface/PBXModule.h>

@class NSArray, NSButton, NSComboBox, NSString, NSTextField;

@interface PBXStringEntryModule : PBXModule
{
    NSButton *okButton;
    NSButton *cancelButton;
    NSTextField *titleField;
    NSComboBox *comboBox;
    NSString *_title;
    NSArray *_comboBoxItems;
    NSString *_resultString;
    id _modalDelegate;
    SEL _didEndSel;
    BOOL _isAppModal;
}

+ (id)sharedStringEntryModule;
- (void)comboBoxSelectionDidChange:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (id)comboBox:(id)arg1 completedString:(id)arg2;
- (unsigned long long)comboBox:(id)arg1 indexOfItemWithStringValue:(id)arg2;
- (id)comboBox:(id)arg1 objectValueForItemAtIndex:(long long)arg2;
- (long long)numberOfItemsInComboBox:(id)arg1;
- (void)cancelButtonAction:(id)arg1;
- (void)okButtonAction:(id)arg1;
- (id)resultString;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)runModalWithComboBoxItems:(id)arg1 relativeToWindow:(id)arg2 modalDelegate:(id)arg3 didEndSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (long long)runModalWithComboBoxItems:(id)arg1;
- (void)_cleanupAfterRunning;
- (id)_panelPreparedToRunWithComboBoxItems:(id)arg1;
- (id)title;
- (void)setTitle:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithModuleNibName:(id)arg1;
- (struct CGSize)viewMaxSize;
- (struct CGSize)viewMinSize;
- (id)moduleWindowFrameAutosaveName;
- (unsigned long long)moduleWindowStyleMask;
- (Class)moduleWindowClass;
- (id)loadModuleWindow;

@end

