//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsInterface/XCBreakpointActionModule.h>

@class NSButton, NSTextField, NSTextView;

@interface XCBreakpointAppleScriptActionModule : XCBreakpointActionModule
{
    NSTextView *_script;
    NSButton *_compile;
    NSButton *_test;
    NSTextField *_status;
    NSTextField *_instructions;
}

- (void)prepareFocus;
- (void)_compile:(id)arg1;
- (void)_test:(id)arg1;
- (void)updateBreakpointAction:(id)arg1;
- (void)setupBreakpointAction:(id)arg1;

@end

