//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsInterface/XCDiffTableComparatorView.h>

@interface XCDiffOutlineComparatorView : XCDiffTableComparatorView
{
}

+ (Class)_viewClass;
+ (Class)_dataSourceClass;
+ (void)initialize;
- (id)_toolTipForDiffDescriptor:(id)arg1;
- (BOOL)_scrollDiffHunkMarkerToVisible:(id)arg1;
- (struct CGSize)mergeViewContentSize;
- (struct CGSize)rightViewContentSize;
- (struct CGSize)leftViewContentSize;
- (void)diffContext:(id)arg1 didAddDiffDescriptor:(id)arg2;

@end

