//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsInterface/XCElementButtonCellDisplay.h>

@interface XCElementCheckBoxCellDisplay : XCElementButtonCellDisplay
{
}

- (void)installLocalDataDelegateForDisplayer:(struct NSObject *)arg1;
- (void)configureForControlSize:(unsigned long long)arg1 font:(id)arg2;

@end

