//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsInterface/XCElementDisplay.h>

@class NSCell, NSColor;

@interface XCElementDisplayRect : XCElementDisplay
{
    NSColor *_foregroundColor;
    NSColor *_backgroundColor;
    NSCell *_backgroundCell;
}

- (void)dealloc;
- (void)displayer:(struct NSObject *)arg1 drawBackground:(struct CGRect)arg2 forFrame:(struct CGRect)arg3;
- (id)backgroundCell;
- (void)setBackgroundCell:(id)arg1;
- (id)backgroundColor;
- (void)setBackgroundColor:(id)arg1;
- (id)foregroundColor;
- (void)setForegroundColor:(id)arg1;
- (id)init;

@end

