//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DevToolsInterface/PBXInspectorPaneModule.h>

@class NSArray, NSTableColumn;

@interface XCFileTargetsInspectorPane : PBXInspectorPaneModule
{
    NSTableColumn *_chooseColumn;
    NSArray *_targetSettings;
}

+ (unsigned long long)panelPosition;
+ (id)alternateLabel;
+ (id)label;
+ (id)inspectableClasses;
+ (BOOL)canInspectItems:(id)arg1;
- (BOOL)tableView:(id)arg1 shouldTrackCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (void)_stopListeningForProjectChanges;
- (void)_startListeningForProjectChanges;
- (void)_itemsChangedInProject:(id)arg1;
- (void)currentInspectedItemsChanged:(id)arg1;
- (void)viewDidLoad;
- (void)_updateTargetSettings;
- (void)_addRef:(id)arg1 toList:(id)arg2;
- (id)targetSettings;
- (void)setTargetSettings:(id)arg1;
- (id)_references;
- (id)_project;
- (void)dealloc;

@end

