//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBXIndexingEngine.h"

@class NSDictionary;

@interface XCNibFileIndexingEngine : PBXIndexingEngine
{
    NSDictionary *_nibContents;
}

+ (id)indexableFileTypes;
+ (void)initialize;
- (void)indexFileAtAbsolutePath:(id)arg1 withSettings:(id)arg2;
- (void)_indexModeledObject:(id)arg1;
- (void)_indexKeysOfModeledObject:(id)arg1;
- (void)_indexOutletsOfModeledClass:(id)arg1;
- (void)_indexActionsOfModeledClass:(id)arg1;
- (void)_indexModeledClass:(id)arg1;
- (void)dealloc;
- (id)initWithProjectIndex:(id)arg1;

@end

