//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface NSTransformerKeyValuePair : NSObject
{
    NSMutableDictionary *_referenceDictionary;
    NSString *_key;
    id _value;
}

- (BOOL)isEqual:(id)arg1;
- (id)value;
- (void)setValue:(id)arg1;
- (id)key;
- (void)setKey:(id)arg1;
- (BOOL)validateKey:(id *)arg1 error:(id *)arg2;
- (id)referenceDictionary;
- (void)setReferenceDictionary:(id)arg1;
- (void)dealloc;
- (id)initWithKey:(id)arg1 value:(id)arg2;
- (id)init;

@end

