//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSColor, NSImage, NSString, XDCompartmentGraphic, XDCompartmentItem;

@interface XDCompartment : NSObject <NSCoding>
{
    XDCompartmentGraphic *_compartmentGraphic;
    id _identifier;
    NSImage *_iconImage;
    NSString *_label;
    NSColor *_backgroundColor;
    id _objectValue;
    XDCompartmentItem *_compartmentItem;
    struct CGSize _compartmentItemMinSize;
    struct _XDCompartmentFlags _cFlags;
}

+ (Class)defaultCompartmentItemClass;
+ (void)initialize;
- (BOOL)isEditable;
- (void)setEditable:(BOOL)arg1;
- (struct CGSize)compartmentItemMinSize;
- (void)setCompartmentItemMinSize:(struct CGSize)arg1;
- (id)compartmentItemAtIndex:(long long)arg1;
- (id)compartmentItem;
- (id)objectValue;
- (void)setObjectValue:(id)arg1;
- (id)backgroundColor;
- (void)setBackgroundColor:(id)arg1;
- (BOOL)drawsBackground;
- (void)setDrawsBackground:(BOOL)arg1;
- (id)label;
- (void)setLabel:(id)arg1;
- (id)iconImage;
- (void)setIconImage:(id)arg1;
- (id)identifier;
- (void)setIdentifier:(id)arg1;
- (id)compartmentGraphic;
- (void)setCompartmentGraphic:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithIdentifier:(id)arg1;

@end

