//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSearchField, XDTableView;

@interface XDGraphicFinder : NSObject
{
    XDTableView *_tableView;
    NSSearchField *_searchField;
}

+ (void)initialize;
- (void)_searchFieldAction:(id)arg1;
- (void)_tableViewAction:(id)arg1;
- (void)dealloc;
- (id)init;

@end

